### ISSUE TITLE
error in TabbedPage

### ISSUE THREAD

**Issue by huyusong** [alexrainman/CarouselView#45] opened 2016-12-27 02:47 UTC
hello!
i found an error  with ( CirclePageIndicator.OnDraw ), 
this is Exception:
System.NullReferenceException: Object reference not set to an instance of an object.

and ScreenShot:
![image](https://cloud.githubusercontent.com/assets/8465319/21489109/d1178084-cc21-11e6-99f9-6c16a81b7f48.png)

**Comment by huyusong** [comment] 2016-12-27 02:50
![image](https://cloud.githubusercontent.com/assets/8465319/21489153/3d975040-cc22-11e6-94e7-444fc25e4ca9.png)

**Comment by alexrainman** [comment] 2016-12-27 03:10
I can ship small fix for that. I wonder how its happening. How are creating the control and assigning its source?

**Comment by huyusong** [comment] 2016-12-27 03:15
this is my code:
    public CarouselViewControl carView;
   carView = new CarouselViewControl
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.White,
                HeightRequest = 200,
                ItemTemplate = new DataTemplate(typeof(hCachedImage)),
                ItemsSource = new List<AdvertisItem>(),
                InterPageSpacing = 10,
                PageIndicatorTintColor = ColorHelper.White,
                CurrentPageIndicatorTintColor = ColorHelper.DeepBlue,
                ShowIndicators = true,
                Arrows = true
            };

   AdvTask = new Thread(new ThreadStart(AutoLoopAdv));
            AdvTask.Start();

   private void LoadAdvList()
        {
            var list = new List<AdvertisItem>()
                {
                    new AdvertisItem
                    {
                        Source = "http://www.hprogram.com/JuZhenShoppingWCF/Content/img/0a66b4b48c804c3280cdeff6ae8b2e622016081212522661.png"
                    },
                    new AdvertisItem
                    {
                        Source = "http://www.hprogram.com/JuZhenShoppingWCF/Content/img/0b4e5e4800a0473d8ef1e7cda2a08e9d2016090211480779.png"
                    }
                };
            carView.ItemsSource = list;
        }

   private void AutoLoopAdv()
        {
            while (!IsClose)
            {
                Thread.Sleep(3000);
                Device.BeginInvokeOnMainThread(() =>
                {
                    try
                    {
                        if (carView.ItemsSource.Count > 0)
                        {
                            var index = 0;
                            if (carView.Position == carView.ItemsSource.Count - 1)
                            {
                                index = 0;
                            }
                            else
                            {
                                index = carView.Position + 1;
                            }
                            carView.SetCurrentPage(index);
                        }
                    }
                    catch (Exception)
                    {
                        
                    }
                });
            }
        }

**Comment by huyusong** [comment] 2016-12-27 03:15
![image](https://cloud.githubusercontent.com/assets/8465319/21489444/c47ef39e-cc25-11e6-8149-caccce19098b.png)
![image](https://cloud.githubusercontent.com/assets/8465319/21489446/c97b20c0-cc25-11e6-8827-c6270ceeff01.png)
![image](https://cloud.githubusercontent.com/assets/8465319/21489447/cb2f2114-cc25-11e6-9deb-4825c7c08734.png)
![image](https://cloud.githubusercontent.com/assets/8465319/21489450/cecb1cec-cc25-11e6-9547-221703a56e15.png)

**Comment by huyusong** [comment] 2016-12-27 03:17
it have 3 pages in TabbedPage
i Chang page  in These 3pages,  and the error happening

**Comment by huyusong** [comment] 2016-12-27 03:18
but if just have 2 pages ,  no error

**Comment by huyusong** [comment] 2017-01-01 16:10
hello!:

i found the reason of this problem;

i use CarouseView in TabbedPage,  i change page1 to page 3, one by one .

and when  click page1, the page will  jump to page1 from page 3;

and at this time :  
in Code  (CirclepageIndicator.cs  - OnDraw(Canvas canvas) )
mViewPager.Adapter == null,  

so the CarouseView is empty now 
![image](https://cloud.githubusercontent.com/assets/8465319/21581913/c5ed0726-d07f-11e6-9fb2-4ed24b0380d8.png)


but  if  jump to page1 from page2,  it's  normal.

so ,why!!!!

**Comment by huyusong** [comment] 2017-01-01 16:15
these 2 imgs  are from urlSource,  and the ImageView is (CachedImage)

**Comment by huyusong** [comment] 2017-01-01 17:24
i understood。。。。 
if  at FormsApplicationActivity mode,  it's normal
but if at FormsAppCompatActivity mode,  it's problem

so ,the problem can fix ?  please fix it !   thank you very much !

**Comment by huyusong** [comment] 2017-01-02 01:44
[http://www.hprogram.com/JuZhenShoppingDownLoad/App4.zip](url)
this is my test project, please !

**Comment by huyusong** [comment] 2017-01-02 01:47
![image](https://cloud.githubusercontent.com/assets/8465319/21583939/4adf2db0-d0d0-11e6-8d4b-282e08abdf98.png)
in this picture,  will error .

and you delete the red code, change the green code to [FormsApplicationActivity],  will no error

**Comment by alexrainman** [comment] 2017-01-03 19:16
Related to #46

**Comment by alexrainman** [comment] 2017-01-03 19:20
I am sorry to tell you that CarouselView inside TabbedPage won't work. The issue is not related to my plugin. TabbedPage somehow Dispose the view when it's not visible and doesn't load it again when swipe. I will try to find why, but you should build a custom tabs with XAML.

**Comment by alexrainman** [comment] 2017-01-03 19:20
Take a look at issue #48.

**Comment by alexrainman** [comment] 2017-01-03 20:32
Please check at this repo for a solution: https://github.com/alexrainman/TabbedCarouselView

**Closed by alexrainman** 2017-01-03 20:32 UTC
Labels: duplicate

**Comment by alexrainman** [comment] 2017-05-04 16:59
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment] 2017-05-04 19:26
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
