### ISSUE TITLE
[Android] CarouselView showing blank on Xamarin.Forms 3.x

### ISSUE THREAD

**Issue by ngkien1530** [alexrainman/CarouselView#428] opened 2018-07-10 08:40 UTC
Hi,
I'm using Carousel View (v 5.2) on Xamarin Forms 3.x (Android Only). I tested out on many versions of Xamarin 3.x, none of them work, result in a blank view. iOS is still working good.
Please update the project. Thank you
And yes, I did call the Renderer.Init();

**Comment by less0** [comment] 2018-07-10 09:02
Are you showing the `CarouselViewControl` on a modal page? It was the issue for me, it refused to display when added to a modal page, but was displayed when I showed the page non-modally.

This looks like a dupe of #417

**Comment by ngkien1530** [comment] 2018-07-10 09:53
No, it isn't. It's just a normal Content Page

**Comment by less0** [comment] 2018-07-10 12:28
> It's just a normal Content Page

This does not mean that it's not displayed modally.

**Comment by nosweat** [comment] 2018-07-23 02:37
We have the same bug encountered on Android, I am using XF3.0.0.561731, Android support 27.0.2.1. 

Our layout/ hierarchy is inside a Tabbar page -> content page -> carouselviewcontrol, if we set the currentpage / default the content page which contains the CarouselViewControl then it shows the control.

It will only disappear once you select another tab and then go back to the content page which has the carousel view. it will appear like 0.5 sec then suddenly disappears.

**Comment by AndriiTsok** [comment] 2018-07-23 04:07
@nosweat I am having exactly the same issue with TabBar and Carousel control.

**Comment by mmichelbb** [comment] 2018-07-27 07:15
I seem to have the same issue. I have a page with two carouselviews, one defined in xaml, another one added programmatically. 
On iOS everything works fine, on Android however, both views are not showing when the page has loaded. However they appear after an orientation change of the device. Turning the orientation back will result in the view having been added programmatically staying there as it is supposed to be, the one added via xaml (sitting in a custom view) seems to keep the with it had in the other orientation (was landscape)

**Comment by AndriiTsok** [comment] 2018-07-28 19:05
@nosweat , @mmichelbb I made a temp fix removing control from my page by OnDisappearing and by adding a new instance of it back by OnAppearing.

**Comment by SpiegelSoft** [comment] 2018-07-29 11:30
I'm adding the CarouselView programmatically. CarouselView 5.2.0, XF 3.1.0.637273. It is not displaying. XAML isn't an option for me.

If I add a HeightRequest and a WidthRequest, the whole app crashes. I'll add the crash details in a separate comment.

Please note that declaring the renderer in the same file that you define the renderer makes it very difficult to declare a custom renderer from F#.

**Comment by SpiegelSoft** [comment] 2018-07-29 11:34
I'm using ReactiveUI for navigation.

**Comment by SpiegelSoft** [comment] 2018-07-30 10:18
Crash details when a HeightRequest and WidthRequest are added:

07-28 13:34:53.652 I/MonoDroid(27032): UNHANDLED EXCEPTION:
07-28 13:34:53.710 I/MonoDroid(27032): Android.Views.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class android.support.design.widget.CheckableImageButton ---> Android.Views.InflateException: Binary XML file line #15: Error inflating class android.support.design.widget.CheckableImageButton ---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c8 a=-1}
07-28 13:34:53.710 I/MonoDroid(27032):    --- End of inner exception stack trace ---
07-28 13:34:53.710 I/MonoDroid(27032):    --- End of inner exception stack trace ---
07-28 13:34:53.710 I/MonoDroid(27032):    --- End of inner exception stack trace ---
07-28 13:34:53.710 I/MonoDroid(27032):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/jenkins/workspace/xamarin-android-d15-7/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
07-28 13:34:53.710 I/MonoDroid(27032):   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <7802aa64ad574c33adca332a3fa9706a>:0 
07-28 13:34:53.710 I/MonoDroid(27032):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <7802aa64ad574c33adca332a3fa9706a>:0 
07-28 13:34:53.710 I/MonoDroid(27032):   at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root) [0x0003a] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-27/mcw/Android.Views.LayoutInflater.cs:619 
07-28 13:34:53.710 I/MonoDroid(27032):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetNativeView () [0x00021] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
07-28 13:34:53.710 I/MonoDroid(27032):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.Element_SizeChanged (System.Object sender, System.EventArgs e) [0x00036] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00029] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:907 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:186 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:565 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.View child, Xamarin.Forms.Rectangle region, Xamarin.Forms.SizeRequest childSizeRequest) [0x0021a] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:318 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.StackLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00092] in D:\a\1\s\Xamarin.Forms.Core\StackLayout.cs:66 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x0014b] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:263 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:223 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:679 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:906 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:186 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:565 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x001cf] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:177 
07-28 13:34:53.710 I/MonoDroid(27032):   at Xamarin.Forms.Platform.Android.ListViewRenderer+Container.OnMeasure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x0004f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewRenderer.cs:468 
07-28 13:34:53.711 I/MonoDroid(27032):   at Android.Views.View.n_OnMeasure_II (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00008] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-27/mcw/Android.Views.View.cs:16110 
07-28 13:34:53.711 I/MonoDroid(27032):   at (wrapper dynamic-method) System.Object.bb52363f-37be-41a0-b38b-822a32cf78d1(intptr,intptr,int,int)
07-28 13:34:53.711 I/MonoDroid(27032):   --- End of managed Android.Views.InflateException stack trace ---
07-28 13:34:53.711 I/MonoDroid(27032): android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class android.support.design.widget.CheckableImageButton
07-28 13:34:53.711 I/MonoDroid(27032): Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class android.support.design.widget.CheckableImageButton

**Comment by nosweat** [comment] 2018-07-30 15:44
@AndriiTsok  i did the same thing, i created a new instance at `OnAppearing()` and handle cleanup at `OnDisappearing()`.  I guess this will be the "hacky" fix to this issue. Not sure why it happens though. I don't want this issue to delay our project. XD

**Comment by mmichelbb** [comment] 2018-08-03 14:17
I found a workaround:
I found out that the initial layout was wrong on android and the view was being rendered way too wide.

Since I know the desired dimensions of my carouselview very exactly, i was able to get it running on Android by overriding OnSizeAllocated and calling another layout pass:

`protected override void OnSizeAllocated(double width, double height)
		{
			if (width > 180)
				myCarouselView.Layout(new Rectangle(90,0,width - 180, 55));
			base.OnSizeAllocated(width, height);
		}`

I know it is not a beauty but at least I can release an app version again if i have to.

**Comment by SinalyVector** [comment] 2018-08-08 10:30
@mmichelbb's workaround work for me

**Comment by dfoulk** [comment] 2018-09-20 17:07
Does the CarouselView re-appear if you turn the device (portrait => landscape => portrait)?

If so, then you've discovered an old issue:
https://github.com/alexrainman/CarouselView/issues/157

I thought our workaround was working, but recently discovered that it no longer seems to work after Xamarin 3.0.

**Comment by alexrainman** [comment] 2018-09-20 17:21
I am currently working on the next release.

**Comment by mmichelbb** [comment] 2018-09-21 08:14
@dfoulk Yes and no:
In a calendar view i am using two carousel views. One is for showing multiple appointments which are being parallel, the other one is for selecting the current day.

Actually the one showing multiple appointments was being displayed properly after doing the portrait -> landscape -> portrait cycle you mentioned.
However the other one (sitting in a custom view element) had the wrong width after the cycle as it had before. 
Strangely enough, after doing my workaround on the view in the custom view the other one never went wrong again.

**Comment by dfoulk** [comment] 2018-09-21 16:12
@mmichelbb For sure. It's just similar to that issue as the "fix" for that issue no longer works. I think the problem (for us) is amplified because we updated XForms to 3.1 in a forked version of this plugin. We had to resort to converting our XAML to code, then redrawing the page inside of the **OnSizeAllocated** method when a rotation is detected (a super brute-force "workaround" that redraws the carousel on device rotation). This is a terrible workaround, but we needed to push a release out immediately and it's the only way we could get this working on both iOS and Android (iOS and Android both were not displaying the images in our carousel until the device was rotated at least once).

I believe it's time for a new repro project so that we can debug this issue. I'll try to put one together, unless @alexrainman already knows what's wrong :)

**Comment by amalwankar** [comment] 2018-10-22 21:08
Hello, @alexrainman  thank you for a great plugin.  Just curious if you have an ETA on the next release?

**Comment by alexrainman** [comment] 2018-11-19 14:09
@ngkien1530 @nosweat @SpiegelSoft @amalwankar can you guys post xaml/cs example so i can reproduce the issue? I am still working on the next release. It will take some time though as i left this abandonware for a year.

**Comment by eddie010** [comment] 2018-11-23 11:55
Having issues on Android as well. The CarouselView works on Android with Xamarin.Forms 3.2.0.871581. Now that I want to update to the latest version (3.4.0.1008975) it stopped working on Android. Very good to see you're working on a big update Alex :) 

Tried to put some xaml/cs example code in here, but GitHub seems to format it really weird.

**Comment by alexrainman** [comment] 2018-11-23 19:20
Yes, I am working on the next release. I still cannot reproduce this with my latest code.

**Comment by Norsotec** [comment] 2019-01-12 20:40
Okay, I had the same issues some month ago so i used the workaround from @mmichelbb (August 2018). After month without any dev work on it, i updated xamarin NuGets and now it's again not working.

so i found a workaround which works for me:

right after InitializeComponent() i put
`ProductCarouselView.PropertyChanged += ProductCarouselView_PropertyChanged;`

And adding this also:
`        private void ProductCarouselView_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            OnSizeAllocated((AppCache.ScreenWidthPix * 0.534), 400);
        }`


And least:

`protected override void OnSizeAllocated(double width, double height) { if (width > 180) ProductCarouselView.Layout(new Rectangle(0, 0, (AppCache.ScreenWidthPix * 0.534), 800)); base.OnSizeAllocated(width, height); }`

so now it's again working for me.. @alexrainman do you still need a code example? I try all my best to provide you with example code and help cause this plugin saved me tons of time man! thanks for your work - full support!

**Comment by alexrainman** [comment] 2019-01-12 20:59
I will be fixing this issue on the next release that will be out soon this month.

**Comment by mikegottlieb** [comment] 2019-02-09 02:24
Just wanted to add that I'm seeing this problem, but not when I initially load my view. It only happens for me after I navigate away and then back to my view.

**Comment by mrxten** [comment] 2019-02-17 21:09
@[mikegottlieb](/mikegottlieb) yes, for me too.
Carousel working only when I opening page with this element second and next times

**Comment by PaulsonMac** [comment] 2019-03-14 07:18
Me too..

**Comment by PaulsonMac** [comment] 2019-03-16 09:34
Hi all,

**Comment by lucidBrot** [comment] 2019-03-26 09:37
Experiencing the same issue: it works on a normally pushed page, but not on a modal page. There, the content is simply blank.

Xamarin Forms 3.6.0.264807 with CarouselView.FormsPlugin 5.2.0

**Comment by PaulsonMac** [comment] 2019-03-26 10:07
@lucidBrot, yes, you're right...! While using PushModal , first time the carousel is blank, the next time it is binded with the carousel items correctly.. Try downgrading your Xamarin Forms to 3.4 and see with PushAsync or setting the app "MainPage" for navigating to the page having this carousel issue.

**Comment by EsmerlinMoya** [comment] 2019-04-12 16:03
@alexrainman We are experiencing the same error that they had mentioned in the previous comments and the workaround as well but it still doesnt work, do you have an estimated date when you solve this?

**Comment by amalwankar** [comment] 2019-05-07 20:07
Hello, @alexrainman thank you for the great plugin. Unfortunately, we are having the same issue mentioned here for XF 3.x.x. Do you have an eta for the fix?

**Comment by dbwelch** [comment] 2019-05-22 22:15
Hi, @alexrainman, same issue mentioned, but, using XF 4.x.  Works great on iOS, Android nothing.

**Comment by alexrainman** [comment] 2019-06-04 15:44
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

**Closed** 2019-06-04 16:13 UTC
Labels: bug

**Comment by AlexandrNikulin** [comment] 2019-07-07 23:41
@alexrainman  Any updates? I have the same issue
at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetNativeView () [0x00075] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0

**Comment by Csharpest118** [comment] 2019-07-10 09:11
I have the same issue; Android devices don't show the carouselview childrens on XF 3.0+.
If I rotate the device once it works.

**Comment by xhashimks** [comment] 2019-08-05 12:19
I am also facing same issue. My case when i switch from one tab to another.

**Comment by Niiikoc** [comment] 2020-09-04 23:08
same here with Xamarin forms 4.8.0.1364 with CarouselView.FormsPlugin 5.2.0
if i run my application in android version 9 & API 27 it works perfectly. On the other hand, when i tried to run in android version 10 & API 28 it doesn't work.
Please update the version of CarouselView
