### ISSUE TITLE
CarouselViewControl not rendered when loading a page from memory

### ISSUE THREAD

**Issue by twentytwokhz** [alexrainman/CarouselView#129] opened 2017-05-23 08:24 UTC
Target control version: 4.2.6

If you create a single instance page that you retrieve with the **Autofac** library such as:
`Bootstrapper.Instance.Container.Resolve<SomeKindOfView>()`
then if that page above contains instances of CarouselViewControl then those will not get rendered with their **ItemTemplate** or get the **Position** set on them => they will be blank

If you want to solve this then I recommend the following workaround: create your own **CustomCarouselViewRenderer** derived from the **CarouselViewRenderer** and override the **OnAttachedToWindow** method like so:

`protected override void OnAttachedToWindow()
		{
			base.OnAttachedToWindow();
			if (Control == null)
			{
				Element.Layout((Element.Parent as View).Bounds);
			}
		}`

Let me know if you have questions
![screenshot_2017-05-23-11-22-51](https://cloud.githubusercontent.com/assets/15191469/26345017/44217c96-3faa-11e7-9ed9-6b7bb1657ae4.png)

**Comment by alexrainman** [comment] 2017-05-23 19:15
What if i want to implement this by default on the control? OnAttachedToWindow is not available for override.

**Comment by twentytwokhz** [comment] 2017-05-23 19:19
I used OnAttachedToWindow on the Android side.
I created a CustomCarouselViewRenderer which I derived from CarouselViewRenderer.
It would be best if it is implemented by default on the control, yes.

**Comment by McFlemchSoda** [comment] 2017-05-24 09:02
@twentytwokhz you say you used **OnAttachedToWindow** on Android, but how would I do this on iOS?

I have created a custom renderer in the iOS project like so:

```
using CarouselView.FormsPlugin.Abstractions;
using CarouselView.FormsPlugin.iOS;
using Xamarin.Forms;

[assembly: ExportRenderer(typeof(CarouselViewControl), typeof(CustomCarouselViewRenderer))]
namespace Example.iOS
{
    public class CustomCarouselViewRenderer : CarouselViewRenderer
    {
        protected override void OnAttachedToWindow()
        {
            base.OnAttachedToWindow();
            if (Control == null)
            {
                Element.Layout((Element.Parent as View).Bounds);
            }
        }
    }
}
```
Yet it says **CustomCarouselViewRenderer.OnAttachedToWindow: no suitable method found to override**

**Comment by twentytwokhz** [comment] 2017-05-24 09:10
@McFlemchSoda The fix I mentioned earlier was only for Android. I haven't gotten to testing on iOS thoroughly but what I saw was that sometimes the control is loaded sometimes it is not.

**Comment by McFlemchSoda** [comment] 2017-05-24 09:21
Thanks for your reply.

My specific issue is when I open the browser from my app and then return back to my app that the CarouselView doesn't get rendered. For now I did a dirty quickfix by initialising the view again in the OnAppearing.

**Comment by alexrainman** [comment] 2017-05-24 11:59
@twentytwokhz OnAttachedToWindow is only available in Android.

**Comment by twentytwokhz** [comment] 2017-05-24 12:32
@alexrainman Yes, sadly...not sure how to do this on iOS. 
The only possible way that I see is to override the **ViewDidAppear** method on the **UIPageViewController** instance. But that variable is not exposed from the **CarouselViewRenderer**
**ViewDidAppear** seems to be the correspondent for the **OnAttachedToWindow** . At least from what I discovered.

**Comment by twentytwokhz** [comment] 2017-05-25 13:41
Found a fix for iOS too :)

**Comment by twentytwokhz** [comment] 2017-05-25 13:47
The problem is found inside the CarouseViewRenderer in method CreateViewController  for iOS
There is no way to simply derive your own CarouselViewRenderer on iOS and do something similar to what I did on Android.

So..for iOS the only option is to copy the whole code from CarouselViewRenderer and add the following inside CreateViewController:

`formsView.Parent = this.Element;

            // UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height
            **if (ElementWidth == 0 || ElementHeight == 0)
            {
                var b = this.Element.Bounds;
                ElementWidth = b.Width;
                ElementHeight = b.Height;
            }**

            var rect = new CGRect(Element.X, Element.Y, ElementWidth, ElementHeight);`

The main problem was that the items that were generated with an ItemTemplate has their **ElementWidth** and **ElementHeight** zero

**Comment by alexrainman** [comment] 2017-05-25 13:59
It seems SizeChanged is never called when loading from memory.

**Comment by twentytwokhz** [comment] 2017-05-25 14:07
@alexrainman Yes, something like that. At first I wanted to trigger SizeChanged manually but then I saw in debug that the width and height were 0 so I simply set them

**Comment by alexrainman** [comment] 2017-05-25 14:30
yeah, but the thing is that the size of the carousel is not always equal to the main window size.

**Comment by tomgilder** [comment] 2017-05-25 15:22
I'm having a similar problem where I'm removing a `CarouselViewControl` from one parent and adding it somewhere else; the element doesn't change dimensions so `SizeChanged` is never fired, and the control ends up blank on Android and iOS.

**Comment by alexrainman** [comment] 2017-05-25 15:33
Let me try to add a fix for it.

**Comment by johnnysbug** [comment] 2017-05-25 16:59
I was having a similar problem when removing the control from a parent and re-adding it. I ended up recreating the control before re-adding it and reapplying bindings. Probably not ideal, but it seems to work.

**Comment by twentytwokhz** [comment] 2017-05-26 06:36
@alexrainman I have MoveToWindow override available on iOS but what should I call here? SizeChanged?

**Comment by twentytwokhz** [comment] 2017-05-26 06:59
@alexrainman My current fixes:

**Android**
```
protected override void OnAttachedToWindow()
 {
       base.OnAttachedToWindow();
       if (Control == null)
       {
           Element.Layout((Element.Parent as View).Bounds);
       }
 }
```

**iOS**

```
 public override void MovedToWindow()
 {
     base.MovedToWindow();
     if (Control == null)
     {
         this.Element_SizeChanged(Element, null);
     }
 }
```

**Comment by twentytwokhz** [comment] 2017-05-26 11:36
Even after this fix..it seems that in my case the first time it shows up ok, the second time it shows up but disappears after a few seconds. Might be related to other code though

**Comment by alexrainman** [comment] 2017-05-26 12:00
I will take a look as soon as i can.

**Comment by alexrainman** [comment] 2017-06-03 17:38
Does this works?

**Comment by TNoronha** [comment] 2017-06-09 15:29
Hello, i believe i still have this problem using version 4.2.9.

When i first open the page, the carouselview still has the items:
![image](https://user-images.githubusercontent.com/27889458/26982366-1c1dc45a-4d30-11e7-8ad9-931d878c5167.png)

Yet, when i navigate, and return to the page, they disappear:
![image](https://user-images.githubusercontent.com/27889458/26982417-4113c5a2-4d30-11e7-8f1c-6029925be71a.png)

This happens in iOS and UWP, haven't tested on android because it's crashing, still figuring out why :)

**Comment by TNoronha** [comment] 2017-06-10 12:23
Had a chance to retest it on Android after using Xamarin.Forms stable release (was using 2.3.5.239-pre3, now using stable 2.3.4.247) and it also happens. The CarouselView has items, but after navigating and loading the page from memory, they disappear.
![screenshot_20170610-131913](https://user-images.githubusercontent.com/27889458/27002703-e2340730-4ddf-11e7-9e16-db866181e279.png)

**Comment by twentytwokhz** [comment] 2017-06-12 14:58
I looked into this but it's extremely annoying. Not sure how to solve this :(

**Comment by twentytwokhz** [comment] 2017-06-13 07:36
I fixed this like so:

**iOS** with modified **CarouselViewRenderer**
`public override void MovedToWindow()
        {
            base.MovedToWindow();
            if (Control == null)
            {
                this.Element_SizeChanged(Element, null);
            }
            else
            {
                //do item reselection
            }
        }`

also modified **SetCurrentPage** (put false on animation when doing SetViewControllers)
`void SetCurrentPage(int position)
        {
            if (pageController != null && Element.ItemsSource != null && Element.ItemsSource?.GetCount() > 0)
            {
                // Transition direction based on prevPosition
                var direction = position >= prevPosition ? UIPageViewControllerNavigationDirection.Forward : UIPageViewControllerNavigationDirection.Reverse;
                prevPosition = position;

                var firstViewController = CreateViewController(position);
                pageController.SetViewControllers(new[] { firstViewController }, direction, false, s =>
                {
                    SetIndicators();

                    // Invoke PositionSelected as DidFinishAnimating is only called when touch to swipe
                    Element.PositionSelected?.Invoke(Element, position);

                    CleanupChildViewControllers();
                });
            }
        }`

**Android**
`protected override void OnAttachedToWindow()
 {
       base.OnAttachedToWindow();
       if (Control == null)
       {
           Element.Layout((Element.Parent as View).Bounds);
       }
      else
      {
          //do item reselection
      }
 }`

**Comment by alexrainman** [comment] 2017-06-14 15:36
What you do the else part? Wht you are putting false in SetCurrentPage -> SetViewControllers?

**Comment by alexrainman** [comment] 2017-06-14 18:12
This code doesn't make sense to me. Why run it only when Control == null?

**Comment by twentytwokhz** [comment] 2017-06-14 19:50
1. Control == null signals that it's the first time it is loaded
2. animation = false because if I let it be Element.animation it will introduce some delays that make the control display the item in a weird way => not visible or in a strange location like not in the middle

Spoiler alert: I'm not an expert on working with renderers
Again..these are my local fixes that made the control behave as I needed.

**Comment by alexrainman** [comment] 2017-06-15 16:44
In iOS this part means the native control rendering will be executed twice

```
      if (Control == null)
      {
           this.Element_SizeChanged(Element, null);
      }
```

In Android when this part is called, the Bounds dimensions are -1

```
       if (Control == null)
       {
           Element.Layout((Element.Parent as View).Bounds);
       }
```

**Comment by alexrainman** [comment] 2017-06-15 16:44
Can you try the Android fix in iOS?

**Comment by twentytwokhz** [comment] 2017-06-16 06:39
I'll give it a try.
The `else` part of the code was used to do item reselection when loading from memory, because the view was empty and setting the **Position** again helped with that.

**Comment by alexrainman** [comment] 2017-06-16 12:30
Can you share a demo project?

**Comment by alexrainman** [comment] 2017-06-18 14:13
Whats the result of your test? I am going to reproduce this myself.

**Comment by GuyMicciche** [comment] 2017-06-20 04:12
I fixed this for Android, here is the fix!

#157

**Comment by alexrainman** [comment] 2017-06-20 12:33
Can someone share a demo project?

**Comment by kcherdch** [comment] 2017-06-29 07:32
Do we have any ETA on when this issue would be resolved?

**Comment by alexrainman** [comment] 2017-06-29 12:00
I guess in the next release. I has been busy.

**Comment by BakersBakers** [comment] 2017-06-30 11:59
I'm requiring this fix too.

**Comment by alexrainman** [comment] 2017-06-30 19:29
Can anyone provide a repo project?

**Comment by tomgilder** [comment] 2017-07-01 08:26
@alexrainman repo here for you: https://github.com/tomgilder/CarouselViewBug129

**Comment by fetbi** [comment] 2017-07-01 16:14
Adding 
```
if (Control == null)
    SetNativeView();
```
Solved my problem.  Looking forward for the update.

```
if (e.NewElement != null)
{
    if (Control == null)
        SetNativeView();

    Element.SizeChanged += Element_SizeChanged;

    // Configure the control and subscribe to event handlers
    if (Element.ItemsSource != null && Element.ItemsSource is INotifyCollectionChanged)
        ((INotifyCollectionChanged)Element.ItemsSource).CollectionChanged += ItemsSource_CollectionChanged;
}

```

**Comment by alexrainman** [comment] 2017-07-01 19:53
@tomgilder this is a very weird way of using the carousel :) I mean, why passing the content of a page to another?

**Comment by tomgilder** [comment] 2017-07-02 11:26
@alexrainman it's really weird, I know 😄

Comes from a wizard interface where from the final summary page we need to push previous pages... because designers like making things complicated 😉

The first example of moving the carousel to a different parent on the same page is much more of a more sane repo!

**Comment by alexrainman** [comment] 2017-07-03 13:26
I found a fix for this on iOS:

```
public override void MovedToSuperview()
{
    if (Control == null)
        Element_SizeChanged(Element, null);

    base.MovedToSuperview();
}

public override void MovedToWindow()
{
    if (Control == null)
       Element_SizeChanged(Element, null);

    base.MovedToWindow();
}
```

**Comment by alexrainman** [comment] 2017-07-03 13:58
Fixed in Android also with this code and -1 as ElementWidth default value to avoid double calling SetNativeView on startup:

```
protected override void OnAttachedToWindow()
{
	if (Control == null)
		Element_SizeChanged(Element, null);
            
        base.OnAttachedToWindow();
}
```

**Comment by BakersBakers** [comment] 2017-07-03 15:27
Do you have an ETA for the next release that fixes the issue above?

**Closed** 2017-07-03 16:02 UTC
Labels: bug

**Comment by BakersBakers** [comment] 2017-07-03 16:17
Will we see this fix released?

**Comment by alexrainman** [comment] 2017-07-03 16:27
As soon as i fix UWP. Later today.

**Comment by GuyMicciche** [comment] 2017-07-03 16:47
Can't wait!

**Comment by alexrainman** [comment] 2017-07-03 17:04
The fix for UWP will be tricky. In UWP when you assign the content of a page to another, when you go back, the previous page is empty :(

**Comment by alexrainman** [comment] 2017-07-03 17:06
It may be a Xamarin.Forms problem, not the control itself.

**Comment by kcherdch** [comment] 2017-07-06 04:58
Hi there, would the fix be out soon for iOS and Android? Seems like the majority of the users that are having issues are on iOS and Android. Could we have a version out for those two first by any chance?

**Comment by hamzaoubouzid** [comment] 2022-04-18 14:00
Hi  @tiagodenoronha  
are you resolve this  problem ?
