### ISSUE TITLE
Carousel miscalculating heights in some cases

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#123] opened 2017-05-11 23:08 UTC
I finally maanged to create a good repro of the issue reported in the PR.
You can download it here: https://www.dropbox.com/s/tli5g1mw97ffm2z/CarouselIssue.zip?dl=0

The layout is still a grid with two rows, with the first row containing the carousel (and a blue button) and the bottom row with a NEW RIDE button.

Expected this:

<img src="https://cloud.githubusercontent.com/assets/873009/25975574/675394dc-36af-11e7-875f-c9ddb49f9415.png" width="200"></img>

With the current setup, this is rendered: As you can see, the carousel spills over the grid row and the bottom row.

<img src="https://cloud.githubusercontent.com/assets/873009/25975580/74940870-36af-11e7-847d-ca8a010d2ef7.PNG" width="200"></img>

**Comment by rkorsak** [comment] 2017-05-17 13:03
Not the package author, but I had a very similar problem not too long ago.  In short, the CarouselView doesn't always render properly in a StackLayout when embedded in certain layouts (in your case, a MasterDetailPage).

You may know this already, but doing either of the following will bypass the problem:

* Not using a MasterDetailPage
* Taking out the StackLayout and just putting the CarouselView in Row 0

I don't know if there's a fix planned for this but, if this is a blocking issue for you like it was for me, avoiding StackLayouts with the CarouselView will get you past it.

**Comment by hardcodet** [comment] 2017-05-17 13:23
Interesting - thanks for the contribution! Not using Master-Detail isn't an option, but I might look into the StackLayout issue. My Layouts are more complex than the sample, so that might not be that easy, but maybe I can hack something with nested Grids. In any case - since Alex wants to merge this into the Xamarin Platform (where it belongs, since Xamarin's version is FooBar), this should be fixed anyway.

@alexrainman Did you get a chance to look into this?

**Comment by alexrainman** [comment] 2017-05-17 23:00
@hardcodet i can confirm the StackLayout sometimes affects how the CarouselView calculates its height, but it seems it's a StackLayout problem and not my control.

I use Size_Changed to get the size of Forms View to size the native views i am adding. It seems StackLayout do something wrong in some cases, which i dont know how to fix.

**Comment by alexrainman** [comment] 2017-05-17 23:01
@hardcodet i guess that will be something Xamarin will fix once the PR is accepted. For now i'm solving what i can solve :)

**Comment by hardcodet** [comment] 2017-05-18 07:24
Hmm, not sure. If I replace the carousel with any other control, the heights are correct, and StackLayout is a super-common control. Also, I don't think you can count on Xamarin to fix this - but you probably can count on a lot of users running into this in real-life apps. Sorry that this one's such a pain!

**Comment by alexrainman** [comment] 2017-05-18 11:44
@hardcodet the thing is i don't know why is this happening :(

**Comment by alexrainman** [comment] 2017-05-18 12:28
@hardcodet the problem here is that you are wrapping the CV with StackLayout, and thats a bad practice.

As as i remove it, the issue is gone.

**Comment by hardcodet** [comment] 2017-05-18 12:39
I know that it's related to the StackLayout, but I don't see how this is bad practice? I have the Carousel and stuff I want to put beneath or on top of it... Unfortunately, I have no experience whatsoever with Xamarin custom controls and layouting. I only did composite controls so far...

(FYI: I solved the issue for myself just using Grids - but you'll have users running into this. I had two differently composed UIs, and both weren't working until I added a grid hack.)

**Comment by alexrainman** [comment] 2017-05-18 13:10
The bad practice is wrap one control with StackLayout :)

**Comment by hardcodet** [comment] 2017-05-18 13:36
Btw, it's the same with a ScrollView. Even if the content of the ScrollView would easily fit on the screen, the carousel takes way too much space in the vertical, pushing the stuff below it off screen. Looking at it, it could actually be exactly 2x as much, but that might be a red herring.

**Comment by bremy** [comment] 2017-06-03 23:36
Hello.  I also have the same problem as described per hardcodet
My CarouselViewModel is implemented using an AbsoluteLayout but I also tried using a StackLayout and the CarouselView is definitely not managing correctly the Height of the content page

After making many tests to do it working, here is a tip to find a way to fix that problem; This is working perfectly until version 2.9.0. After that version impossible to see the full content of the page in particular the bottom part. So in my case "Precedent" and "Suivant" buttons, and also the carousel indicators are not visible
Hope that will help to fix that pb existing since many many versions

**Here the result using version 2.9.0**

![simulator screen shot 4 juin 2017 a 01 18 32](https://cloud.githubusercontent.com/assets/5034603/26757684/dc0e487c-48c4-11e7-852e-8ab7b15bb985.png)

**Here the result using any version after 2.9.0
We see clearly the bottom of the content is no more visible and the top of the content is larger. This means that the height of the content is no more correctly managed after 2.9.0**

![simulator screen shot 4 juin 2017 a 01 31 30](https://cloud.githubusercontent.com/assets/5034603/26757701/e9d5fe5e-48c5-11e7-9491-05da36a87f1a.png)

**Comment by alexrainman** [comment] 2017-06-04 17:43
I still cannot reproduce this or i already fixed it with my current code. Wait for the next release and let me know if the problem is solved.

**Comment by alexrainman** [comment] 2017-06-04 18:47
After running some tests, these are my findings:

1. This layout works with any combination (using the grid, moving the button inside the StackLayout, StackLayout wrapping the carousel only)

```
<Grid x:Name="LayoutRoot"
          Padding="0"
          RowSpacing="0"
          ColumnSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <StackLayout
                     VerticalOptions="FillAndExpand"
                     Grid.Row="0">

            <cv:CarouselViewControl x:Name="CardCarousel"
                                          ItemsSource="{Binding ItemsSource}"
                                          Margin="8"
                                          BackgroundColor="Aqua"
                                          HorizontalOptions="FillAndExpand"
                                          VerticalOptions="FillAndExpand">
                <cv:CarouselViewControl.ItemTemplate>
                    <DataTemplate>
                        <Button Text="hello world 4"
                                BackgroundColor="Blue" />
                    </DataTemplate>
                </cv:CarouselViewControl.ItemTemplate>

            </cv:CarouselViewControl>
        </StackLayout>

        <Button Text="NEW RIDE"
                VerticalOptions="Center"
                Margin="16,32,16,16"
                Grid.Row="1" />
    </Grid>
```

2. Same layout doesn't work when the page is Detail inside a MasterDetailPage.

My conclusion: this issue is not related to the control itself. It is more a Xamarin.Forms issue where StackLayout doesn't calculate height in the right way when used in a Detail page inside a MasterDetailPage.

**Comment by bremy** [comment] 2017-06-05 13:18
Let me know when your new release will be published. I will try it and will let you know about the result
In the mean time, did you have a chance to try with your 2.9.0 version? In my case this is working like a charm. But any version after I definitely can't see neither the bottom buttons, neither the indicators

That could be perhaps useful to debug with the perfect knowledge you have for your lines of code

**Comment by alexrainman** [comment] 2017-06-05 13:23
Version 2.0.8 is out and it works fine with StackLayout unless its part of Detail in MasterDetailPage :)

**Comment by bremy** [comment] 2017-06-05 15:03
I just make a try with your version 4.2.8 and still the same problem like in my screen captures. Bottom buttons and indicators are not visible
I am not using MasterDetailPage at all

my main screen is a ContentPage using a StackLayout
When push a button, I am doing a Navigation.PushAsync to a TabbedPage
Each tabbedPAges "Temsi", "Wintem", "Front", "Satellite", "Radar" are a ContentPage with its Contents
which is a ContentPage using a StackedLayout

this last StackedLayout contains a grid to display an ActivityIndicator, a CarouselView, another grid to display "Precedent" and "Suivant" buttons

And the CarouselView itself dataTemplate is based on an AbosluteView

Once again, with version 2.9.0 all is working nice but no more with any versions after 2.9.0

**Comment by alexrainman** [comment] 2017-06-05 15:07
Can you share a demo of the layout you are using so i can identify the problem? The only difference between 2.9.0 and current is that in the old one the Carousel is initialized on Height property changed and in the current one SizeChanged is used for that matter.

**Comment by bremy** [comment] 2017-06-05 15:17
Yes I am going to try to make a sample project ASAP for you. That will be easier to identify where could be the problem

I will say that with the new versions, the Height of the CarouselView is equal to the screen height. This is why the bottom part is not visible because it becomes hidden by the bottom Tabbed bar. I am suspecting this because my image displayed at the middle of the CarouselView content is not located at the middle of the height that the carouselView should used (like it is well done in version 2.9.0)

**Comment by alexrainman** [comment] 2017-06-05 15:32
It seems the height i get at SizeChanged is not the same i can get at PropertyChanged.

I will test that way as soon i get your demo.

**Comment by hardcodet** [comment] 2017-06-07 10:32
I have another weird issue in that section. I switched to Grid layouts due to the original bug, and just noticed that on IOS, I have a button on grid. The grid is star-sized, and the button just aligned to the bottom:

            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <Button Text="..."
                    Grid.Row="1"
                    VerticalOptions="End"  />

 Now, and this is a reliable reproduction, when I switch back and forth from that carousel page, every *second* time, the button is being moved  down and halfway out of sight. Moving to the second page and back corrects the issue, moving to the second page and back again pushes the button off-screen again:

<img src="https://user-images.githubusercontent.com/873009/26874122-b7bfb6d0-4b7c-11e7-8f0a-8b7cf3faca31.jpg" ></img>

![2017-06-07 12 22 19](https://user-images.githubusercontent.com/873009/26874260-43dd02a8-4b7d-11e7-8230-256bf4ff3fb6.jpg)

**Comment by bremy** [comment] 2017-06-07 21:12
Alex, I find a easy way to reproduce the issue in your Demo sample. Using that lines of code for the first Tab in "MyTabbedPage.xaml", this reproducing the same problem I have in my app. The indicators are no more visible in the CarouselView and the last label "Stop" is not visible as well

	<ContentPage Title="First">
		<StackLayout>
		<Label Text="Start"
		       HorizontalOptions="CenterAndExpand"
               VerticalOptions="StartAndExpand"/>
		<controls:CarouselViewControl x:Name="myCarousel"
                                      HorizontalOptions="FillAndExpand"
                                      VerticalOptions="CenterAndExpand"
                                      AnimateTransition="true"
                                      IndicatorsShape="Circle"
                                      InterPageSpacing="10"
                                      BackgroundColor="Red"
                                      Orientation="Horizontal"
                                      ShowIndicators="true"/>
		<Label Text="Stop"
			    HorizontalOptions="CenterAndExpand"
			    VerticalOptions="EndAndExpand"/>
	    </StackLayout>
	</ContentPage>

**Comment by alexrainman** [comment] 2017-06-14 18:55
There's not fix for this as it seems to be a Xamarin.Forms related issue. When you use StackLayout in a master detail page, it doesn't calculate height in the correct way.

**Comment by bremy** [comment] 2017-06-14 21:19
Alex

Not ure your demo code is using a master detail page. The line of code in exposed in the post are made in your demo code!

Any chance from your side to analyse what was changing between version 2.9.0 and the actual one? Using version 2.9.0 all is working well and impossible to see all the content pages after

Debug both could help to understand why this is ok with 2.9.0?



Envoyé de mon iPad

**Comment by alexrainman** [comment] 2017-06-15 12:45
I cannot reproduce this problem unless the Carousel is wrapped in StackLayout inside a MasterDetail page. In any other scenario it works as expected.

**Comment by alexrainman** [comment] 2017-06-16 12:47
I lost my 2.9.0 source code copy. I have been trying to track the changes i did from that version to current but is a lot :(

**Comment by bremy** [comment] 2017-06-17 13:02
Alex

 

In one post, I gave you the way to reproduce the problem in your demo you are providing with CarouselView

Just few lines of code to change in your demo and you will be able to reproduce outside of any MasterDetail page

 

Use the following lines of code in your file called MyTabbedPage.xaml

Put this for the content of the first Tab in MyTabbedPage

 

You will see immediately the problem displayed

 

Very easy to test

 

Once again, with version 2.9.0 using this type of layout works very well but no more in any version after

 

 

<ContentPage Title="First">

        <StackLayout>

        <Label Text="Start"

               HorizontalOptions="CenterAndExpand"

           VerticalOptions="StartAndExpand"/>

        <controls:CarouselViewControl x:Name="myCarousel"

                                  HorizontalOptions="FillAndExpand"

                                  VerticalOptions="CenterAndExpand"

                                  AnimateTransition="true"

                                  IndicatorsShape="Circle"

                                  InterPageSpacing="10"

                                  BackgroundColor="Red"

                                  Orientation="Horizontal"

                                  ShowIndicators="true"/>

        <Label Text="Stop"

                   HorizontalOptions="CenterAndExpand"

                   VerticalOptions="EndAndExpand"/>

    </StackLayout>

</ContentPage>

 

 

 

De : Alex Rainman [mailto:notifications@github.com] 
Envoyé : vendredi 16 juin 2017 14:48
À : alexrainman/CarouselView
Cc : bremy; Comment
Objet : Re: [alexrainman/CarouselView] Carousel miscalculating heights in some cases (#123)

 

I lost my 2.9.0 source code copy. I have been trying to track the changes i did from that version to current but is a lot :(

**Comment by alexrainman** [comment] 2017-06-17 13:46
I cannot see your entire post :)

**Comment by bremy** [comment] 2017-06-17 14:08
in your demo file MyTabbedPage.xaml, you have these lines of code

`
<ContentPage Title="First">
    <controls:CarouselViewControl x:Name="myCarousel"
         HorizontalOptions="FillAndExpand"
         VerticalOptions="CenterAndExpand"
         AnimateTransition="true"
         IndicatorsShape="Circle"
         InterPageSpacing="10"
         BackgroundColor="Red"
         Orientation="Horizontal"
         ShowIndicators="true"/>
</ContentPage>
`

replace it with

`
<ContentPage Title="First">
    <StackLayout>
       <Label Text="Start"
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="StartAndExpand"/>
      <controls:CarouselViewControl x:Name="myCarousel"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="CenterAndExpand" 
            AnimateTransition="true"
            IndicatorsShape="Circle"
            InterPageSpacing="10"
            BackgroundColor="Red"
            Orientation="Horizontal"
            ShowIndicators="true"/>
        <Label Text="Stop"
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="EndAndExpand"/>
     </StackLayout>
 </ContentPage>
`

**Comment by alexrainman** [comment] 2017-06-17 14:37
I was able to see it happening with small change to your xaml, but again, this is not my control issue. The control gets height from its parent height. In this case, the parent is StackLayout and StackLayout is reporting a wrong height. I cannot do anything about it.

**Comment by alexrainman** [comment] 2017-06-17 14:39
Even going back to creating the Carousel when Height property changed, as version 2.9.0, instead of SizeChanged, the issue is there. If i replace the StackLayout by a Grid, everything works as expected.

**Comment by bremy** [comment] 2017-06-17 22:12
OK I will try with a Grid.
Definitely in 2.9.0 evn using a stack layout this is working well. You have my screen captures  posted 2 weeks ago are showing this. The first screen capture is using a StackLayout like the one I made in your demo

**Closed** 2017-06-17 22:22 UTC
Labels: bug

**Comment by alexrainman** [comment] 2017-06-17 22:24
I have version 2.3.2. Will try adding the changes up to 2.9.0 and see what i can do.

**Comment by bremy** [comment] 2017-06-18 12:15
This is working well with that content using a Grid in your sample. I am going to do similar in my App

```
	<ContentPage Title="First">
		<Grid>
			<Grid.RowDefinitions>
    			    <RowDefinition Height="30" />
    			    <RowDefinition Height="*" />
    			    <RowDefinition Height="30" />
  			</Grid.RowDefinitions>
			<Label Text="Start"
			       HorizontalOptions="CenterAndExpand"
	                       VerticalOptions="StartAndExpand"
			       Grid.Row="0"/>
			<controls:CarouselViewControl x:Name="myCarousel"
	                                      HorizontalOptions="FillAndExpand"
	                                      VerticalOptions="Start"
	                                      AnimateTransition="true"
	                                      IndicatorsShape="Circle"
	                                      InterPageSpacing="10"
	                                      BackgroundColor="Red"
	                                      Orientation="Horizontal"
	                                      ShowIndicators="true"
				              Grid.Row="1"/>
			<Label Text="Stop"
				   HorizontalOptions="CenterAndExpand"
	                           VerticalOptions="EndAndExpand"
				   Grid.Row="2"/>
		</Grid>
	</ContentPage>

```

**Comment by HelenMamalaki** [comment] 2019-01-10 14:33
@alexrainman Even when my carousel view is not in a stacklayout, but in a Grid in my MasterDetailPage it doesn't appear unless I set a specific row height which is not useful for adapting the images size to different Android devices. Is it because the entire page is in a scrollview. Anyone know of a work around for this?

**Comment by gokuldasc** [comment] 2019-03-07 07:27
@alexrainman The carouselview control is not working when put inside Grid or stack layout.  I need to have two controls on one page with their respective labels. I used grid with 4 rows with height for label row to 40 and carosuselview grid row height ="*" .Any ideas? It works fine with one control without any layout

**Comment by alooosh** [comment] 2020-02-15 00:58
> Not the package author, but I had a very similar problem not too long ago. In short, the CarouselView doesn't always render properly in a StackLayout when embedded in certain layouts (in your case, a MasterDetailPage).
> 
> You may know this already, but doing either of the following will bypass the problem:
> 
> * Not using a MasterDetailPage
> * Taking out the StackLayout and just putting the CarouselView in Row 0
> 
> I don't know if there's a fix planned for this but, if this is a blocking issue for you like it was for me, avoiding StackLayouts with the CarouselView will get you past it.

this work for me thanks man
