### ISSUE TITLE
[iOS] Indicator shape shown first as circle also when defined to be square

### ISSUE THREAD

**Issue by hilpara** [alexrainman/CarouselView#223] opened 2017-10-06 15:06 UTC
This happens at least with iOS. When the CarouselView is first load the indicator shape will be circle. When I swipe to the next page, then the indicators will change correctly to square.

**Comment by alexrainman** [comment] 2017-10-09 17:50
I cannot reproduce this.

**Comment by hilpara** [comment] 2017-10-09 20:41
[CarouselIndicatorTest.zip](https://github.com/alexrainman/CarouselView/files/1369776/CarouselIndicatorTest.zip)
Here is a project to show it.

**Comment by alexrainman** [comment] 2017-10-10 19:22
This is a very weird stuff. The thing is that if you don't wrap the page into a NavigationPage, the bug happens. Try wrapping your main page into a NavigationPage and you will see the bug is gone.

**Comment by alexrainman** [comment] 2017-10-10 19:34
That's the only solution I can offer you for now. It seems to be a Xamarin.Forms glitch.

**Comment by hilpara** [comment] 2017-10-11 06:38
Unfortunately it doesn't help in my situation. The carousel view where I'm using this feature is a view inside another carousel view and I don't know how I could wrap it to NavigationPage.
But thanks for your great work!

**Comment by alexrainman** [comment] 2017-10-11 11:16
Look in my repos. Theres one to create nested carousels.

**Comment by hilpara** [comment] 2017-10-11 14:22
Your nested example behaves exactly as mine. If you enable the indicators for the nested one and make them square, they will also first appear round and will be updated to square when swiped. The primary carousel view will have square indicators from the beginning if enabled.

**Comment by alexrainman** [comment] 2017-10-11 14:26
This may be a glitch on iOS or XF because the code that makes them square is running. No idea why the show up like circles.

**Comment by alexrainman** [comment] 2017-10-11 14:27
Can you try programmatically set position to 1 then to 0 on startup?

**Comment by hilpara** [comment] 2017-10-11 14:33
It doesn't help. I guess it has something to do with view redrawing.

**Comment by hilpara** [comment] 2017-10-11 14:36
I also have problems with nested carousel view on android. Sometimes it doesn't draw anything on the nested carousel view. I have to swipe it and then it will show the first page not the second as you would think.

**Comment by alexrainman** [comment] 2018-03-27 12:57
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Closed by alexrainman** 2018-03-27 12:57 UTC
Labels: cantfix
