### ISSUE TITLE
Unhandled exception when using StaticResource

### ISSUE THREAD

**Issue by TastesLikeTurkey** [alexrainman/CarouselView#211] opened 2017-09-11 01:41 UTC
So far the `CarouselViewControl` has been working great for me, but I just hit a problem.

This:
 ```
<Label Text={Binding Name, Converter={StaticResource StringConverter}} />
```
works just fine outside of the `CarouselViewControl` and displays as it should. But if I stick it inside the control, I get an `UnhandledException` crash. Taking the binding converter out fixes the crash (but obviously I do actually need the converter, so taking it out isn't really an option.)

The converter is never even hit when inside the control.

**Comment by alexrainman** [comment] 2017-09-11 01:42
Please provide a demo so i can find the reason of the exception.

**Comment by robjames** [comment] 2017-09-12 16:11
To confirm, I also get the same when using`Style="{StaticResource Clock}"` so I imagine it's the static resource that's the issue.

**Comment by TastesLikeTurkey** [comment] 2017-09-12 16:17
@robjames Ah, that hadn't occurred to me. I've edited the issue title to make it easier for others to find.

**Comment by alexrainman** [comment] 2017-09-13 14:15
Where is the static resource located? because i have on the view itself and it works.

**Comment by TastesLikeTurkey** [comment] 2017-09-13 14:21
@alexrainman  For me, it's:

```
<ContentPage ...>
    <ContentPage.Resources>
        <ResourceDictionary>
            <converters:MyConverter x:Key="MyConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <cvc:CarouselViewControl ...>
        <cvc:CarouselViewControl.ItemsSource>
            <x:Array Type={x:View}>
                <Label Text={Binding Value, Converter={StaticResource MyConverter}} />
            </x:Array>
        </cvc:CarouselViewControl.ItemsSource>
    </cvc:CarouselViewControl>
</ContentPage>
```

I wrote that by memory, so there might be a few typos, etc.

**Comment by alexrainman** [comment] 2017-09-13 14:34
@TastesLikeTurkey @robjames i can confirm that unless you put the converter in the View itself, it is not going to work. That's because, when the Xamarin.Forms.View is converted to Native, that's done at a level where there's no access to the ContentPage where the control is located neither to the Application global resources located in App.xaml.

**Comment by alexrainman** [comment] 2017-09-13 14:34
Im closing it because i don't have a way to solve it.

**Comment by TastesLikeTurkey** [comment] 2017-09-13 14:34
@alexrainman Fair enough. Thanks for providing a workaround!

**Closed by alexrainman** 2017-09-13 14:34 UTC

**Comment by TastesLikeTurkey** [comment] 2017-09-13 23:07
@alexrainman  Do you have a basic example of putting the converter in the view? I can't seem to get it to work.
