### ISSUE TITLE
(UWP) Entry virtual keybord not pushing up

### ISSUE THREAD

**Issue by predalpha** [alexrainman/CarouselView#138] opened 2017-05-30 21:43 UTC
First thank you for your contribution !

I encounter one issue with the CarouselView  embedding an entry on Windows mobile 10 platform (works fine on Droid)

If an entry is at the bottom of the Carouselview, when you click on it, it makes appear the virtual keyboard.
However, the keyboard dont push up the content upside and then overlay the editor which make impossible to see what we re typing.

Any workaround or fix for that ?

[CarouselViewKeyboard.zip](https://github.com/alexrainman/CarouselView/files/1039779/CarouselViewKeyboard.zip)

**Comment by alexrainman** [comment] 2017-05-31 11:51
Are you wrapping your view in ScrollView?

**Comment by predalpha** [comment] 2017-05-31 12:12
hi Alex, 

Yes i do. Below sample code

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
             xmlns:local="clr-namespace:CarouselViewKeyboard"
             x:Class="CarouselViewKeyboard.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <DataTemplate x:Key="cvTemplate">
                <ScrollView Orientation="Vertical">
                    <StackLayout Orientation="Vertical" Spacing="50">
                        <Label Text="Line 1" />
                        <Label Text="Line 2" />
                        <Label Text="Line 3" />
                        <Label Text="Line 4" />
                        <Label Text="Line 5" />
                        <Label Text="Line 6" />
                        <Label Text="Line 7" />
                        <Label Text="Line 8" />
                        <Label Text="Line 9" />

                        <Entry Keyboard="Text" 
                                       Text="Click on me !" 
                                       HorizontalOptions="FillAndExpand"
                                        />
                    </StackLayout>
                </ScrollView>
            </DataTemplate>
        </ResourceDictionary>
    </ContentPage.Resources>


    <controls:CarouselViewControl Orientation="Horizontal" 
                                  BackgroundColor="Red"
                                  IndicatorsTintColor="Black"
                                  InterPageSpacing="10" 
                                  Position="0" 
                                  ShowIndicators="True"
                                  ShowArrows="True"
                                  ItemsSource="{Binding SourceListe}" 
                                  ItemTemplate="{StaticResource cvTemplate}"
                                  VerticalOptions="FillAndExpand" 
                                  HorizontalOptions="FillAndExpand">
    </controls:CarouselViewControl>

</ContentPage>
```

Are you suggesting me to put controls inside a grid with many rows instead of scrollview ?
Will the scrollview will be compatible in the future on UWP phone as for Android platform ?

**Comment by alexrainman** [comment] 2017-05-31 12:15
Let me try to reproduce this.

**Comment by predalpha** [comment] 2017-06-03 19:55
Hi Alex,

Have you managed to reproduce this bug ?

Got another question 
Will your control definitiveley replace Xamarin Carouselview one ?

**Comment by alexrainman** [comment] 2017-06-03 20:24
I fixing other bugs but this one is on my list. Ans yes, the control will replace Xamarin's one. The PR is under review.

**Comment by predalpha** [comment] 2017-06-03 20:38
Good news as you provide nice support and updates.
Was insisting about that virtual keyboard issue cause its very blocking (even if the windows mobile community is a very small one). But anyway, i havent publish my app yet. 

Thanks for your answers and that control !

Below a capture of your control for an image gallery. (no input on this ;) )
![capture](https://cloud.githubusercontent.com/assets/13038769/26756925/5cc870ae-48ad-11e7-908f-d0f9f90721eb.PNG)

**Comment by alexrainman** [comment] 2017-06-18 14:50
I don't have a device so i cannot reproduce this. Basically, i don't know whats happening neither how to fix it.

**Comment by predalpha** [comment] 2017-06-18 15:34
Not really need to own a device. Have 
you tried with mobile debug emulator ?

No focus on any control
![capture1](https://user-images.githubusercontent.com/13038769/27261865-022a77a0-544c-11e7-91cf-887a1151e8fd.png)

Focus on one
![capture2](https://user-images.githubusercontent.com/13038769/27261876-20afa45c-544c-11e7-9a20-90e58cd95d99.png)

As you can see, the keyboard hide the textbox.

Previously, i was using xamarin own carousel control and they have the same issue.
Maybe in the renderer, including the content into a native uwp scrollview could solve that ?

**Comment by alexrainman** [comment] 2017-06-18 15:38
Mobile debug emulator?

**Comment by alexrainman** [comment] 2017-06-18 15:39
Sorry i am not a UWP expert

**Comment by predalpha** [comment] 2017-06-18 15:52
No worries, under visual studio, you can see that option to select a device.

![capture](https://user-images.githubusercontent.com/13038769/27262000-a4f88e66-544e-11e7-84d0-89d92feb824e.PNG)

If you only have localmachine , you can edit your visual studio installation in order to have more debug emulators.

**Comment by alexrainman** [comment] 2017-06-18 18:52
This piece of code will fix the issue. I will run some tests to see if i can incorporate it into the Renderer:

```
public MainPage()
{
    this.InitializeComponent();

    LoadApplication(new SoftInput.App());
    _originalHeight = ApplicationView.GetForCurrentView().VisibleBounds.Height;

    InputPane.GetForCurrentView().Showing += MainPage_Showing;
    InputPane.GetForCurrentView().Hiding += MainPage_Hiding;
}

private double _originalHeight;
private void MainPage_Hiding(InputPane sender, InputPaneVisibilityEventArgs args)
{
    this.Height = _originalHeight;
    this.VerticalAlignment = Windows.UI.Xaml.VerticalAlignment.Stretch;
}

private void MainPage_Showing(InputPane sender, InputPaneVisibilityEventArgs args)
{
    this.Height = _originalHeight - args.OccludedRect.Height;
    this.VerticalAlignment = Windows.UI.Xaml.VerticalAlignment.Top;
}
```

**Comment by predalpha** [comment] 2017-06-19 08:01
Thank you Alex for your support. Ill give you a feedback as soon as i check your solution. (probably tomorrow)

**Comment by predalpha** [comment] 2017-06-22 10:39
ive tried your code inside an extended Carousel renderer with no success.

**Comment by predalpha** [comment] 2017-06-22 10:59
Below a custom renderer base on : [https://social.msdn.microsoft.com/Forums/windows/en-US/711a3399-33de-4c20-9080-12379ad48a12/u81-universal-app-for-windows-81-move-the-text-box-above-the-keyboard?forum=wpdevelop](url)

```
[assembly: ExportRenderer(typeof(CarouselViewControl), typeof(CarouselViewRendererEx))]
namespace CarouselViewKeyboard.UWP
{

    public class CarouselViewRendererEx : CarouselView.FormsPlugin.UWP.CarouselViewRenderer
    {
        private double _offSet;

        protected override void OnElementChanged(ElementChangedEventArgs<CarouselViewControl> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Showing -= CarouselViewRendererEx_Showing;
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Hiding -= CarouselViewRendererEx_Hiding;
            }

            if (e.NewElement != null)
            {
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Showing += CarouselViewRendererEx_Showing;
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Hiding += CarouselViewRendererEx_Hiding;
            }

        }

        private void CarouselViewRendererEx_Hiding(Windows.UI.ViewManagement.InputPane sender, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs args)
        {
            var trans = new Windows.UI.Xaml.Media.TranslateTransform();
            trans.Y = 0;
            this.RenderTransform = trans;
            args.EnsuredFocusedElementInView = false;
        }

        private void CarouselViewRendererEx_Showing(Windows.UI.ViewManagement.InputPane sender, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs args)
        {
            _offSet = (int)args.OccludedRect.Height;
            args.EnsuredFocusedElementInView = true;
            var trans = new Windows.UI.Xaml.Media.TranslateTransform();
            trans.Y = -_offSet;
            this.RenderTransform = trans;
        }

    }
```

**Comment by alexrainman** [comment] 2017-06-22 12:51
Does this works?

**Comment by predalpha** [comment] 2017-06-22 14:10
For the sample i gave in the first comment yes it seems to work fine.
Ill try with a more complex page and give another feedback.

**Comment by predalpha** [comment] 2017-06-22 14:17
It's a first shot code. It solves the issue but it may need some improvements.
Will try to make some improvements but not sure i can achieve a perfect solution.

**Comment by alexrainman** [comment] 2017-06-22 15:03
Will try something myself. I want to ship a new version and theres some keyboard fix for Android, so it makes sense i include this also.

**Comment by predalpha** [comment] 2017-06-22 15:15
Sure, happy to have a new release.
Have you test on your side the code ?  
Anyway it seems to work and if i can make some improvements, ill share it.

**Comment by alexrainman** [comment] 2017-06-22 16:09
Will let you know it works or not later today. Thanks

**Comment by alexrainman** [comment] 2017-06-23 12:18
This fix partially works. The top part of the Carousel pages is not visible/scrollable. It only scrolls from the field that has the focus to the bottom.

**Comment by predalpha** [comment] 2017-06-23 19:27
You re right, after more tests, if the Textbox is on top, it scrolls down and you cannot edit it so... its not a good solution.
I ll look for a better one and will comment here when i find better.

**Comment by predalpha** [comment] 2017-06-24 00:07
Ok seems i found better. I forked your solution and edited 
**CarouselView\CarouselView.FormsPlugin.UWP\FlipViewControl.xaml**

I replace 
` <FlipView x:Name="flipView">`

by following code

```
 <FlipView x:Name="flipView">
            <FlipView.ItemsPanel>
                <ItemsPanelTemplate>
                    <StackPanel Orientation="Horizontal" AreScrollSnapPointsRegular="True" />
                </ItemsPanelTemplate>
            </FlipView.ItemsPanel>
   </FlipView>
```

For more informations you can read this link as it is a windows bug for flipview control.
By changing the flipview item template like this, we' re loosing virtualization. The content is totally generated instead of being loading on scroll.

The author explains a more complete caching solution for virtualization but i think this should do the trick without.

[http://www.feo2x.com/posts/2015-12-06-flipview-and-problems-with-input-controls-part-1/](url)

**Comment by alexrainman** [comment] 2017-06-24 00:19
I will take a look for sure. I use virtualization in Android and iOS and i tried to do it in UWP but couldnt :)

**Comment by alexrainman** [comment] 2017-06-24 00:44
Sorry, i misunderstood. Currently theres no virtualization in UWP.

**Comment by predalpha** [comment] 2017-06-24 01:28
Your code is using native UWP/UAP flipview to make a Xamarin CarouselView for windows platform.
By default, the flipview controls virtualize its content. (native behavior, nothing that you have to handle yourself)

This is not an issue itself but according to the article of fe02x, this control has a bug with input controls inside due to the native virtualization behavior.

By changing the flipview template (as you can see in my previous post), it will disable native virtualization. 

Was just speaking about virtualization in order to give a more complete answer but it seems to work nice disabling it.

**Comment by alexrainman** [comment] 2017-06-24 02:17
The thing is i couldn't find the way to use the virtualization because the differences between Xamarin DataTemplateSelector and UWP DataTemplateSelector.

**Comment by predalpha** [comment] 2017-06-25 20:48
Maybe there is some misunderstanding with my previous posts.

Have you tried to replace your code inside -> **CarouselView\CarouselView.FormsPlugin.UWP\FlipViewControl.xaml**

`<FlipView x:Name="flipView">`

by 

```
 <FlipView x:Name="flipView">
            <FlipView.ItemsPanel>
                <ItemsPanelTemplate>
                    <StackPanel Orientation="Horizontal" AreScrollSnapPointsRegular="True" />
                </ItemsPanelTemplate>
            </FlipView.ItemsPanel>
   </FlipView>
```
Seems to work perfectly on UWP Phone and solves the issue.


*********************************************************************************************
*********************************************************************************************
*********************************************************************************************


I was speaking about virtualization only because that solution breaks the windows flipview default virtualization template. As you can see below the default native style of flipview is using a **VirtualizingStackPanel**  :

```
<Style TargetType="FlipView">
...
<Setter Property="ItemsPanel">
  <Setter.Value>
    <ItemsPanelTemplate>
      <VirtualizingStackPanel AreScrollSnapPointsRegular="True" Orientation="Horizontal" />
    </ItemsPanelTemplate>
  </Setter.Value>
</Setter>

```

I think there is a misunderstanding because on Android, you have to handle virtualization manually as opposite to flipview UWP control which is doing that natively.

**Comment by alexrainman** [comment] 2017-06-25 20:52
I dont have to handle virtualization manually in Android neither in iOS. I am not using virtualization in UWP because of DataTeplate limitations.

**Comment by predalpha** [comment] 2017-06-25 21:00
Sorry to be wrong on that. Misunderstanding was coming from me.
But what do you think about the solution ?

**Comment by predalpha** [comment] 2017-06-26 16:48
Finally i've implemented that solution into a CarouselRenderer.
No test on Vertical Carousel but seems to work fine in horizontal way.

**Comment by alexrainman** [comment] 2017-06-26 16:49
Good. Will add it and release a new version.

**Comment by predalpha** [comment] 2017-06-26 16:54
thank you

**Comment by predalpha** [comment] 2017-07-04 15:47
Sorry but my code isnt working. Got unspecified error on 4.4.1 version.
Seems can bind carousel itemssource but template binding inside causes crash.

**Comment by predalpha** [comment] 2017-07-04 18:57
So weird, when im debugging and take some time to go through breaking points, i dont have the error.

**Comment by mattrichnz** [comment] 2017-07-14 08:58
**Alex - this change in v4.41 is not good and is breaking badly on UWP.**
Changing the default `ItemsPanelTemplate` from a `VirtualizingStackPanel` to a `StackPanel ` results in "Error HRESULT E_FAIL has been returned from a call to a COM component" being thrown all over the place. 

We've had to revert back to v4.40 to get stability back on UWP. 

CarouselViewFormsPlugin is a great package and we look forward to seeing it become part of Xamarin.Forms, but changes like this _need to be made more carefully._ Simply overriding the default XAML template for `FlipView` to fix an edge case on Windows Phone is not good practice. The default template is no doubt provided for good reason.

Alex, are you possibly able to please revert this change and release v4.43?

**Comment by predalpha** [comment] 2017-07-14 09:12
Hi Alex,

Well, the version 4.1 is not enough stable for me. Got memory issues and errors due to the change of virtualizing panel to a classic stackpanel. 

_While i was writing this post i saw @mattrichnz cross post one and i sincerely apologize since i gave the tricks what causes that issue_ 

So i revert to 4.0 and made a renderer to comply with my purposes. That seems to work with binding keeping the virtualizingstackpanel.

Below the custom renderer wrote with pain. It need to be strongly tested and wait for users feedbacks / improvements : 

```
[assembly: ExportRenderer(typeof(CarouselViewControl), typeof(CarouselViewRendererEx))]
namespace CarouselViewKeyboard.UWP
{

    public class CarouselViewRendererEx : CarouselView.FormsPlugin.UWP.CarouselViewRenderer
    {
        private bool inputPaneIsVisible = false;
        private ScrollViewCache CurrentScrollViewer = null;

        protected override void OnElementChanged(ElementChangedEventArgs<CarouselViewControl> e)
        {
            base.OnElementChanged(e);


            if (e.OldElement != null)
            {
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Showing -= CarouselViewRendererEx_Showing;
            }

            if (e.NewElement != null)
            {
                Windows.UI.ViewManagement.InputPane.GetForCurrentView().Showing += CarouselViewRendererEx_Showing;
            }

        }

        private void CarouselViewRendererEx_Hiding(Windows.UI.ViewManagement.InputPane sender, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs args)
        {
            //0. Hiding s'execute lorsque l'inputPane disparait
            //On sort de la fonction si cela ne concerne pas notre Flipview
            if ((!inputPaneIsVisible) | (CurrentScrollViewer == null)) return;


            //1. Reverting ScrollViewerContainer to its originals datas
            CurrentScrollViewer.RestoreLayout();

            //2. On détache l'inputPane
            inputPaneIsVisible = false;
            CurrentScrollViewer = null;
            Windows.UI.ViewManagement.InputPane.GetForCurrentView().Hiding -= CarouselViewRendererEx_Hiding;
            args.EnsuredFocusedElementInView = false;
        }

        private async void CarouselViewRendererEx_Showing(Windows.UI.ViewManagement.InputPane sender, Windows.UI.ViewManagement.InputPaneVisibilityEventArgs args)
        {
            //0. Showing s'execute lors de le prise et perte du focus
            //On sort de la fonction dans le cas où l'InputPane est déjà affiché
            if (inputPaneIsVisible) return;

            //1. On récupère l'élément avec le focus
            var FocusElement = Windows.UI.Xaml.Input.FocusManager.GetFocusedElement() as Windows.UI.Xaml.FrameworkElement;
            if (FocusElement == null)
            {
                return;
            }

            Windows.UI.Xaml.Controls.FlipView fl = Control.FindName("flipView") as Windows.UI.Xaml.Controls.FlipView;
            Windows.UI.Xaml.FrameworkElement fItem = fl.SelectedItem as Windows.UI.Xaml.FrameworkElement;
            var parentScrollViewer = FindVisualChild<Windows.UI.Xaml.Controls.ScrollViewer>(fItem);

            if (parentScrollViewer == null)
            {
                return;
            }

            //2. L'élément est-il un descendant de notre Flipview (il faut le déterminer ici car InputPane_Showing peut être lancé depuis un controle appartenant à un autre conteneur
            if (!IsVisualChildOf(parentScrollViewer, FocusElement))
            {
                return;
            }

            //3.1 On stocke l'état de l'inputPane afin de prévenir l'execution de cette fonction sur la perte de focus
            inputPaneIsVisible = true;
            //3.2 On attache la fonction InputPane Hiding
            Windows.UI.ViewManagement.InputPane.GetForCurrentView().Hiding += CarouselViewRendererEx_Hiding;

            //3.3 Saving _original datas to revert on InputPane_Hiding
            CurrentScrollViewer = new ScrollViewCache(parentScrollViewer);

            //3. Performing adaption to InputPane
            await Task.Delay(200);
            await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
            {

                //4.Scrolling to FocusElement if it is obscured by InputPane
                //4.1 Getting Position of FocusElement

                Windows.UI.Xaml.Media.GeneralTransform gtPageRelative = FocusElement.TransformToVisual(Windows.UI.Xaml.Window.Current.Content);
                Windows.Foundation.Point positionPointPageRelative = gtPageRelative.TransformPoint(new Windows.Foundation.Point(0, 0));

                //4.2 Is FocusElement Obscurred
                //  YES -> Scrolling to it
                if (args.OccludedRect.Y <= positionPointPageRelative.Y + FocusElement.RenderSize.Height)
                {
                    //5.Updating Scrollviewer to adapt with InputPane
                    CurrentScrollViewer.AdjustLayout(args.OccludedRect.Height + FocusElement.RenderSize.Height);

                    //6. Scrolling to good position
                    var verticalOffset = -1 * (args.OccludedRect.Y - positionPointPageRelative.Y) + FocusElement.RenderSize.Height + parentScrollViewer.VerticalOffset;
                    CurrentScrollViewer.ScrollTo(verticalOffset);

                    //Indicates to the system no to ensure FocusElement in view cause we re doing it manually
                    args.EnsuredFocusedElementInView = true;
                }

            });

        }



        private childItemType FindVisualChild<childItemType>(Windows.UI.Xaml.DependencyObject obj, string name) where childItemType : Windows.UI.Xaml.FrameworkElement
        {
            for (int i = 0; i < Windows.UI.Xaml.Media.VisualTreeHelper.GetChildrenCount(obj); i++)
            {
                Windows.UI.Xaml.DependencyObject child = Windows.UI.Xaml.Media.VisualTreeHelper.GetChild(obj, i);

                if (child is childItemType && ((Windows.UI.Xaml.FrameworkElement)child).Name == name)
                    return (childItemType)child;
                else
                {
                    childItemType childOfChild = FindVisualChild<childItemType>(child, name);

                    if (childOfChild != null)
                        return childOfChild;
                }
            }

            return null;
        }

        private childItemType FindVisualChild<childItemType>(Windows.UI.Xaml.DependencyObject obj) where childItemType : Windows.UI.Xaml.FrameworkElement
        {
            for (int i = 0; i < Windows.UI.Xaml.Media.VisualTreeHelper.GetChildrenCount(obj); i++)
            {
                Windows.UI.Xaml.DependencyObject child = Windows.UI.Xaml.Media.VisualTreeHelper.GetChild(obj, i);

                if (child is childItemType)
                    return (childItemType)child;
                else
                {
                    childItemType childOfChild = FindVisualChild<childItemType>(child);

                    if (childOfChild != null)
                        return childOfChild;
                }
            }

            return null;
        }

        private bool IsVisualChildOf(Windows.UI.Xaml.DependencyObject Parent, Windows.UI.Xaml.DependencyObject Child)
        {
            bool IsChildOf = false;
            var _childParent = Windows.UI.Xaml.Media.VisualTreeHelper.GetParent(Child) as Windows.UI.Xaml.DependencyObject;

            if (_childParent != null)
            {
                if (Parent == _childParent)
                {
                    IsChildOf = true;
                }
                else
                {
                    return IsVisualChildOf(Parent, _childParent);
                }
            }

            return IsChildOf;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
            {
                try
                {
                    Windows.UI.ViewManagement.InputPane.GetForCurrentView().Showing -= CarouselViewRendererEx_Showing;
                    Windows.UI.ViewManagement.InputPane.GetForCurrentView().Hiding -= CarouselViewRendererEx_Hiding;
                }
                catch (Exception)
                {
                }
            }
        }

        public class ScrollViewCache
        {
            //Reference to the ScrollViewContainer
            public Windows.UI.Xaml.Controls.ScrollViewer _originalContainer { get; private set; }

            private Windows.UI.Xaml.Thickness _padding;
            private Windows.UI.Xaml.Controls.ScrollMode _verticalScrollMode;

            public ScrollViewCache(Windows.UI.Xaml.Controls.ScrollViewer Container)
            {
                _originalContainer = Container;
                this._padding = Container.Padding;
                this._verticalScrollMode = Container.VerticalScrollMode;
            }

            public void AdjustLayout(double AdjustingHeight)
            {
                _originalContainer.Padding = new Windows.UI.Xaml.Thickness(_padding.Left, _padding.Top, _padding.Right, _padding.Bottom + AdjustingHeight);
                _originalContainer.VerticalScrollMode = Windows.UI.Xaml.Controls.ScrollMode.Enabled;
                _originalContainer.UpdateLayout();
            }

            public void ScrollTo(double verticalOffset)
            {
                _originalContainer.ChangeView(_originalContainer.HorizontalOffset, verticalOffset, _originalContainer.ZoomFactor, true);
            }

            public void RestoreLayout()
            {
                _originalContainer.Padding = this._padding;
                _originalContainer.VerticalScrollMode = this._verticalScrollMode;
                _originalContainer.UpdateLayout();
            }
        }
    }
}
```

**Comment by alexrainman** [comment] 2017-07-14 12:46
I will go back to VirtualizationPanel in the next release. Does this custom renderer fix the soft keyboard issue?

**Comment by predalpha** [comment] 2017-07-14 15:53
For a standard use, it seems to work and gives the ability to scroll inside the full carousel content but there are so many layouts configurations to test with padding, margin, nesting, ...

Some margin settings can cause some issue for auto scrolling to correct position but as we can scroll we can see what we're typing.

Moreover i have only tested this with Left / Right swiping in vertical orientation.

It probably requires more feedbacks and improvements. 
Whats your opinion ? Have you tried it @alexrainman ?

**Comment by alexrainman** [comment] 2017-07-15 14:31
@predalpha can you paste here only the code changes you added?

**Comment by predalpha** [comment] 2017-07-15 16:12
Hi @alexrainman ,

it is an independant renderer overriding yours. 
If you want to test it, put that code into your demo project (simply create a file class and paste all code inside).

Else you can check with my OnElementChanged method to adapt your renderer implementation and paste all others methods inside. (be carefull i add a signature method to your FindVisualChild, and i have overrided your disposing method).

If you need more assistance, just tell me. I ll have more time tomorrow.

Regards

**Comment by mattrichnz** [comment] 2017-08-07 07:39
@alexrainman Just wondering when we can possibly expect 4.4.3 with the switch back to VirtualizationPanel? We had to revert back several versions to get stability back on UWP again, so are keen to update the NuGet package when available.

**Comment by alexrainman** [comment] 2017-08-07 12:25
I was traveling and completely off the grid. I think by the end of week.

**Comment by alexrainman** [comment] 2017-08-31 21:29
I just released a new version but a fix for this still not there. I had to go back to VirtualizationStackPanel for stability purposes. Let's see how i can fix this.

**Comment by alexrainman** [comment] 2018-03-27 12:58
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Closed by alexrainman** 2018-03-27 12:58 UTC
Labels: bug
