### ISSUE TITLE
[iOS] 'NSInternalInconsistencyException' while using carouselview plugin

### ISSUE THREAD

**Issue by chandshiakasz** [alexrainman/CarouselView#468] opened 2018-10-26 07:34 UTC
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Don't know about flushed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x115623d00; frame = (0 0; 414 559.339); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c603c0a0>>'

**Comment by chandshiakasz** [comment] 2018-10-26 07:36
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No view controller managing revealed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x11d37a240; frame = (0 0; 414 559.339); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c242ca20>>'

**Comment by chandshiakasz** [comment] 2018-10-26 07:37
Getting this exception while using carsoule plugin @alexrainman  can you provide any resolution , if it is known bug

**Comment by alexrainman** [comment] 2018-11-10 23:53
Can you provide a demo reproducing the issue?

**Comment by alexrainman** [comment] 2018-12-01 15:49
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks

**Comment by mikecamimo** [comment] 2019-01-02 05:59
We were seeing the same error in our application, however it is looking like it has nothing to do with the CarouselView. Our problem was that we were removing an item from a ListView (each item had a CarouselView of scrollable images), but we were doing it in such a way that the CarouselView could still be scrolling to an image after the item was removed. The user would tap say a delete icon overlaying the CarouselView to remove the item from the list, but they would keep scrolling the images while the code was removing the item from the list. This caused the app to crash on iOS. On android it seemed to handle the use case without a crash.

Not sure if this is the same issue others are having, but its worth looking into.

**Comment by saskl** [comment] 2019-01-14 09:08
In our application we are loading the images for the CarouselView first from cache and then reload them from the server. If you are swiping through the gallery while the images are reloaded the app crashes with this error. If your connection is good you need to be very fast for this to occur but with a bad connection this can happen after some seconds.
On Android this does not cause any issues.

**Comment by leo-mck** [comment] 2019-01-30 16:01
I am having this problem too. I think @saskl is right, the problem seems to happen when we change ItemsSource while changing the selected item on the control. I have made a very basic app that reproduces this problem, try to manually change pages and if this happen while setting Items on code, it crash.

[App7.zip](https://github.com/alexrainman/CarouselView/files/2813363/App7.zip)

**Comment by David-Lamar** [comment] 2019-04-17 18:46
@alexrainman We've experienced this issue where I work.

The issue happens when the child view controllers are disposed of (Lines 919 - 923 of iOS CarouselViewImplementation.cs) during a scrolling/animation event. This can happen if carousel items are updated via some sort of background task and the user is scrolling through the carousel.

I've implemented a fix locally in my work project -- I keep track of when animation and scrolling events are happening as well as when the native view is getting updated. Using these, I disallow scrolling or updating temporarily depending on if the other is going.

I didn't create a pull request for your repo because I've changed the code significantly and I may have broken pieces that aren't specific to our project. If you would like to see the changes I've made, let me know.

**Comment by alexrainman** [comment] 2019-06-04 15:47
Will try to reproduce this.

**Comment by alexrainman** [comment] 2019-09-19 23:55
This will be fixed in the next release.

**Closed by alexrainman** 2019-09-19 23:55 UTC
Labels: bug, enhancement

**Comment by aismaniotto** [comment] 2020-02-07 19:04
Facing same problem 😕
