### ISSUE TITLE
PositionSelected fired Twice !

### ISSUE THREAD

**Issue by jeromeliger** [alexrainman/CarouselView#247] opened 2017-11-05 10:52 UTC
After a week, nobody respond to my previous issue report... anybody here ?

I'm trying other things with PositionSelected Event, and when the "PositionSelected" event is triggered, I send a "MessaginCenter message" to my viewmodel.

Everything works... except that the "PositionSelected" is fired TWICE when I change my VM position.

`Position="{Binding CarouselWeekPosition}"
ItemTemplate="{Binding CarouselWeekTemplate}"
ItemsSource="{Binding WeekViewModels}"
PositionSelected="CarouselWeek_PositionSelected"`

Easy to reproduce, just add a breakpoint on the PositionSelected Event.

If you want the code I can send a new version, but it's the same that in my [last issue request](https://github.com/alexrainman/CarouselView/issues/241), with just adding "PositionSelected" event)

Any help ? informations ?

**Comment by alexrainman** [comment] 2017-11-07 13:31
This doesn't supposed to be happening but i will take a look.

**Comment by alexrainman** [comment] 2017-11-07 14:16
PositionSelected is only called twice when you add a new week to the upper carousel.

**Comment by jeromeliger** [comment] 2017-11-08 13:34
Nop, even if I just "swipe" from one day to another (or one week to another), the PositionSelected is fired twice.

By the way, another "hack" is preventing this, by saving the last position arg :

`
public partial class CustomPage : ContentPage
{
	public CustomPage()
	{
		InitializeComponent();
	}

	private int saveweekposition = -1;
	private void CarouselWeek_PositionSelected(object sender, CarouselView.FormsPlugin.Abstractions.PositionSelectedEventArgs e)
	{
		if (e.NewValue != saveweekposition)
		{
			saveweekposition = e.NewValue;
			MessagingCenter.Send<CustomPage, int>(this, "CarouselWeekPosition", e.NewValue);
		}
	}

	private int savedayposition = -1;
	private void CarouselDay_PositionSelected(object sender, CarouselView.FormsPlugin.Abstractions.PositionSelectedEventArgs e)
	{
		if (e.NewValue != savedayposition)
		{
			savedayposition = e.NewValue;
			MessagingCenter.Send<CustomPage, int>(this, "CarouselDayPosition", e.NewValue);
		}
	}
}

I'm investingating too... and I'll send you my sample updated soon.

Thanks in advance.
`

**Comment by jelle-vdst** [comment] 2017-11-10 09:38
I also see PositionSelected being fired multiple times, but only in UWP, android and IOS only fire it once.

When the Carousel is being displayed it even fires it 4 times apparently (the NewValue is even changes like this -> 0 - 1 0 0, Android and IOS only fire 0)

When you start scrolling in UWP, the event is always fired twice (with the sam exact NewValue)

**Comment by alexrainman** [comment] 2017-11-10 14:53
I cannot reproduce this in iOS and Android. Will take a look on UWP.

**Comment by alexrainman** [comment] 2017-11-18 18:54
In iOS there's a chance PositionSelected is called twice because Element_SizeChanged is triggered twice by XF rendering engine.

**Comment by jeromeliger** [comment] 2017-11-20 10:51
Ok, thanks a lot for your investigation time !

**Comment by Jyosua** [comment] 2018-01-11 01:50
This is happening to me on Android. Just swiping or setting the position in code results in two PositionSelected events being fired with the same e.NewValue.

I'm using a Nexus 6P emulator with API 25, though I can't imagine it being device specific.

**Comment by Jyosua** [comment] 2018-01-12 00:22
So it appears this is caused on Android when you have the app in fullscreen mode. When you tap on a field to edit text, the keyboard attempts to launch, but fails and instead the app is removed from being fullscreen. If you tap again, the keyboard will show up and it will work. However, from that point on, the CarouselView will fire the PositionSelected event twice (sometimes more) with the same value, every time the position is changed.

**Comment by alexrainman** [comment] 2018-03-27 12:57
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Closed by alexrainman** 2018-03-27 12:57 UTC
Labels: cantfix
