### ISSUE TITLE
Carousel View Issue when rotating the screen

### ISSUE THREAD

**Issue by hashimks** [alexrainman/CarouselView#406] opened 2018-05-24 06:04 UTC
Hello,

I am using this carousel view in which my DataTemplate is stacklayout which contains an Image control.
After I run the app, I am able to see the view of say 5 images properly say in portrait mode. When i rotate the screen to landscape, it retains the image position which is same as in portrait and not properly aligned.
After couple of scrolls back and forth, it aligns correctly.  Again if i rotate the device back to Portrait, it shows the image which is positioned when it is in landscape mode and here also same problem. Can you please help me? I am stuck here

**Comment by AndreiMisiukevich** [comment] 2018-05-28 22:00
@hashimks hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView

Because, this plugin was merged to XF..

**Comment by GamesAgeddon** [comment] 2018-07-26 05:53
Already reported in January but unfortunately closed. https://github.com/alexrainman/CarouselView/issues/310

**Comment by alexrainman** [comment] 2018-11-19 18:00
Trying to reproduce this.

**Comment by alexrainman** [comment] 2018-11-19 18:01
@hashimks how are creating your DataTemplate? XAML? DataTemplateSelector?

**Comment by alexrainman** [comment] 2018-12-01 15:54
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks

**Comment by mclillill** [comment] 2019-01-11 09:49
@contrix09 Android? then there is a workaround. in the view, use this snippet.
```csharp
protected override void OnSizeAllocated(
			double dblWidth,
			double dblHeight
			)
		{
			base.OnSizeAllocated(dblWidth, dblHeight);

				// fix for carouselview orientation bug on android
				if(Device.RuntimePlatform == Device.Android)
				{
					m_ctrlIssueCarousel.Orientation = 
						CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Vertical;
					m_ctrlIssueCarousel.Orientation = 
						CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Horizontal;
				}
		}
```

**Comment by contrix09** [comment] 2019-01-11 10:05
@mclillill  Cheers! Thanks, it worked.

**Comment by jbtamaresgit** [comment] 2019-03-03 05:42
@mclillill Is m_CtrlIssueCarousel would be the name of your carousel in your xaml?

**Comment by mclillill** [comment] 2019-03-04 09:17
@jbtamaresgit correct.

**Comment by alexrainman** [comment] 2019-06-04 15:38
@mclillill I want to understand what this actually does.

**Comment by alexrainman** [comment] 2019-06-04 15:41
@hashimks the problem here is you are wrapping each image with a StackLayout, which I know it has problems calculating its size inside a CarouselView. Can you try removing the stack?

**Comment by mclillill** [comment] 2019-06-05 07:11
@jbtamaresgit yes, m_CtrlIssueCarousel ist the name of the carousel.

**Comment by mclillill** [comment] 2019-06-05 07:13
@alexrainman I don't know. It's just a workaround. It triggers a new layout cycle but not sure why carousel breaks in the first place.

**Comment by alexrainman** [comment] 2019-07-04 00:09
The fix for this should be as simple as including this in the MainActivity:

```cs
Xamarin.Forms.Application.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);
```

**Comment by alexrainman** [comment] 2019-09-20 16:02
With or without the workaround, images wrapped by StackLayout don't resize on screen rotation, even with Aspect=Fill. If you want to use a StackLayout, you have to provide the expected size.

Without the StackLayout, everything works as expected, with or without the workaround.

**Closed by alexrainman** 2019-09-20 16:02 UTC
Labels: workaround

**Comment by Spiggers** [comment] 2020-07-17 14:17
> @contrix09 Android? then there is a workaround. in the view, use this snippet.
> 
> ```cs
> protected override void OnSizeAllocated(
> 			double dblWidth,
> 			double dblHeight
> 			)
> 		{
> 			base.OnSizeAllocated(dblWidth, dblHeight);
> 
> 				// fix for carouselview orientation bug on android
> 				if(Device.RuntimePlatform == Device.Android)
> 				{
> 					m_ctrlIssueCarousel.Orientation = 
> 						CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Vertical;
> 					m_ctrlIssueCarousel.Orientation = 
> 						CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Horizontal;
> 				}
> 		}
> ```

This also worked for me. This issue is still around in July 2020. Perhaps another issue, perhaps different scenario, but I had a simple carousel view with a datatemplate set in XAML. when the screen rotated, the carouselview did not resize, so I ended up with badly layed out pages. Something then "decached" aftera a while as scrolling back and forward and waiting causes a re-render. 

Setting the orientation to vertical, then back to horizontal as described worked

**Comment by W4lm4s** [comment] 2020-07-27 23:38
@Spiggers 
For me this workaround was ok, but the arrows on the carousel disapear after the orientation change.
The carousel itself seems well resized, the issue looks to be on children, and I didn't find a way to force them to properly redraw or getting more available space.

My little add  :
        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);

            if (this.width != width || this.height != height)
            {
                this.width = width;
                this.height = height;
                var items = carousel.ItemsSource;
                carousel.ItemsSource = Enumerable.Empty<ContentView>();
                carousel.ItemsSource = items;
            }
}
the width & height are initialize to 0 in the ctor.

I noticed in the source code, doing this would trigger a call to : SetArrowsVisibility() & (this is aguess) a call to Element_SizeChanged (indirectly, via events), which is calling SetNativeView();

July 2020.
