### ISSUE TITLE
[IOS] Crash : NSInternalInconsistencyException Reason: No view controller managing visible view

### ISSUE THREAD

**Issue by nhdanh** [alexrainman/CarouselView#296] opened 2017-12-21 07:56 UTC
I was installed plugin. When I go to the page, back and go to new page (any page has a scrollview). It crash. I got the exception. How to fix it ? Thank you

> 
> `2017-12-21 14:49:12.339 CTWCCare.iOS[87332:1284990] pageController.ChildViewControllers count = 3
> 2017-12-21 14:49:12.610 CTWCCare.iOS[87332:1284990] *** Assertion failure in -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.33.6/UIPageViewController.m:2067
> Unhandled Exception:
> 
> Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: No view controller managing visible view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7fb746924150; frame = (0 0; 375 100); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x60800162d840>>
> Native stack trace:
> 	0   CoreFoundation                      0x0000000118b7112b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x0000000119ab1f41 objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000118b762f2 +[NSException raise:format:arguments:] + 98
> 	3   Foundation                          0x000000010edf7d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
> 	4   UIKit                               0x000000010bccd264 -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:] + 1156
> 	5   UIKit                               0x000000010bdef490 -[_UIQueuingScrollView _notifyDelegateDidEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:] + 139
> 	6   UIKit                               0x000000010bdeeac0 __78-[_UIQueuingScrollView _enqueueAnimatedScrollInDirection:withView:completion:]_block_invoke + 69
> 	7   UIKit                               0x000000010bdea854 -[_UITransitionState cleanupWithFinishedState:completedState:] + 35
> 	8   UIKit                               0x000000010bdedd6e -[_UIQueuingScrollView _cleanUpCompletionState:didFinish:didComplete:] + 96
> 	9   UIKit                               0x000000010bdf14c0 -[_UIQueuingScrollView _didEndScroll:] + 337
> 	10  UIKit                               0x000000010bdebe40 -[_UIQueuingScrollView _scrollViewAnimationEnded:finished:] + 104
> 	11  UIKit                               0x000000010b4bac53 -[UIAnimator stopAnimation:] + 422
> 	12  UIKit                               0x000000010b4bb3a1 -[UIAnimator _advanceAnimationsOfType:withTimestamp:] + 282
> 	13  QuartzCore                          0x00000001110ec2b8 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 684
> 	14  QuartzCore                          0x000000011122c894 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
> 	15  CoreFoundation                      0x0000000118b00899 __CFMachPortPerform + 169
> 	16  CoreFoundation                      0x0000000118b007d9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
> 	17  CoreFoundation                      0x0000000118b00741 __CFRunLoopDoSource1 + 465
> 	18  CoreFoundation                      0x0000000118af8524 __CFRunLoopRun + 2596
> 	19  CoreFoundation                      0x0000000118af7889 CFRunLoopRunSpecific + 409
> 	20  GraphicsServices                    0x000000011b49d9c6 GSEventRunModal + 62
> 	21  UIKit                               0x000000010b3295d6 UIApplicationMain + 159
> 	22  ???                                 0x0000000138544ea8 0x0 + 5240016552
> 	23  ???                                 0x0000000138544ad3 0x0 + 5240015571`

**Comment by alexrainman** [comment] 2017-12-21 13:12
There’s a problem with ScrollView in latest XF releases. Wrap it with ContentView or StackLayout.

**Comment by nhdanh** [comment] 2017-12-22 00:30
oh my form many control. I need a ScrollView to scroll form. The app also crash when my form has listview.  any way to resolve it.

**Comment by nhdanh** [comment] 2017-12-22 01:53
I wrapped CarouselView in ContentView or StackLayout. So it still crash

**Comment by alexrainman** [comment] 2017-12-22 02:01
No no, wrap the ScrollViews inside your carousel pages with StackLayout :)

**Comment by nhdanh** [comment] 2017-12-22 02:11
I just remove ScrollView. It still crash

I wrap scrollview inside stacklayout. Still crash. 

This is my form. Can you help me to fix it ? 

> <ScrollView VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
        <Grid VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <Grid ColumnSpacing="0" RowSpacing="0">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>
                <ff:CachedImage BitmapOptimizations="True" Source="bg_home.png" Aspect="AspectFill"></ff:CachedImage>

                <StackLayout Grid.Row="0" HorizontalOptions="FillAndExpand" VerticalOptions="End" >
                    <StackLayout IsVisible="{Binding IsLogin}" Padding="10" Spacing="0">
                       
                    </StackLayout>
                </StackLayout>

                <Grid Grid.Row="2" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" ColumnSpacing="1" RowSpacing="1">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"></ColumnDefinition>
                        <ColumnDefinition Width="*"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="*"></RowDefinition>
                        <RowDefinition Height="*"></RowDefinition>
                        <RowDefinition Height="*"></RowDefinition>
                    </Grid.RowDefinitions>
                    
                </Grid>
                <StackLayout Grid.Row="3">
                    <cv:CarouselViewControl  
                        HeightRequest="100"
                        Orientation="Horizontal" 
                        ItemsSource="{Binding ListHinhAnh}"
                        Position="{Binding Position}"
                        IndicatorsShape="Circle"
                        ShowIndicators="True">
                        <cv:CarouselViewControl.ItemTemplate>
                            <DataTemplate>
                                <ContentView>
                                    <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                                        <ff:CachedImage Aspect="AspectFit" 
                                                        
                                                        DownsampleUseDipUnits="True"
                                                        Source="{Binding Image}"
                                                        HorizontalOptions="FillAndExpand"
                                                        VerticalOptions="FillAndExpand" >
                                        </ff:CachedImage>
                                    </Grid>
                                </ContentView>
                            </DataTemplate>
                        </cv:CarouselViewControl.ItemTemplate>
                    </cv:CarouselViewControl>
                </StackLayout>
            </Grid>
            <controls:Indicator />
        </Grid>
    </ScrollView>

>

**Comment by alexrainman** [comment] 2017-12-22 02:29
```xml
        <ScrollView>
            <StackLayout>
                <Grid ColumnSpacing="0" RowSpacing="0">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>
                    
                    <ff:CachedImage Grid.Row="0" BitmapOptimizations="True" Source="bg_home.png" Aspect="AspectFill"/>>

                    <StackLayout Grid.Row="1" IsVisible="{Binding IsLogin}" Padding="10" Spacing="0">
                    </StackLayout>

                    <Grid Grid.Row="2" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" ColumnSpacing="1" RowSpacing="1">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*"></ColumnDefinition>
                            <ColumnDefinition Width="*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="*"></RowDefinition>
                            <RowDefinition Height="*"></RowDefinition>
                            <RowDefinition Height="*"></RowDefinition>
                        </Grid.RowDefinitions>
                        <!-- this is my grid control -->
                    </Grid>
                    
                    <cv:CarouselViewControl Grid.Row="3"  
                        HeightRequest="100"
                        Orientation="Horizontal" 
                        ItemsSource="{Binding ListHinhAnh}"
                        Position="{Binding Position}"
                        IndicatorsShape="Circle"
                        ShowIndicators="True">
                        <cv:CarouselViewControl.ItemTemplate>
                            <DataTemplate>
                                <ff:CachedImage Aspect="AspectFit"
                                                DownsampleUseDipUnits="True"
                                                Source="{Binding Image}"
                                                HorizontalOptions="FillAndExpand"
                                                VerticalOptions="FillAndExpand" >
                                </ff:CachedImage>
                            </DataTemplate>
                        </cv:CarouselViewControl.ItemTemplate>
                    </cv:CarouselViewControl>
                    
                </Grid>
                <controls:Indicator />
            </StackLayout>
        </ScrollView>
```

**Comment by nhdanh** [comment] 2017-12-22 03:21
very sad. I change the layout to your recommend. So it still crash with this error log :(

**Comment by nhdanh** [comment] 2017-12-22 03:23
this is my homepage. This crash when I go to login page, and back to homepage many times. In login page, I use scrollview.

**Comment by alexrainman** [comment] 2017-12-22 03:24
Can you remove ky control entirely and try?

**Comment by nhdanh** [comment] 2017-12-22 03:29
I remove all controls. I just keep the CarouselView to test. It crashed.

I remove CarouselView and test again. It normally 

I was screen recorded this error. 

[https://youtu.be/5KhkY7TFVwo](url)

**Comment by nhdanh** [comment] 2017-12-22 07:40
I looking forward to you help me fix it

**Comment by alexrainman** [comment] 2017-12-24 02:38
Unless you can provide me a demo to reproduce the issue i cannot help.

**Comment by nhdanh** [comment] 2017-12-25 00:32
I was post the video to show the error I got. What's info I can provide for you to help me. 

https://youtu.be/5KhkY7TFVwo

**Comment by nhdanh** [comment] 2017-12-25 03:54
I describe the error detail again for you to help me fix error. 

I have a 2 page. HomePage and some page using ScrollView. My HomePage has a CarouselView to slide image. When I go to any page in my app and back to HomePage many time. It crashed. 

The HomePage.xaml I posted in previous post. You can see it.  

This is video I recorded the error the detail for you: 
https://youtu.be/8N7BM-tyN3s

I try remove each element in my HomePage to test it again. When I remove the CarouselView in my Homepage. The error not happen. It happen only I using CarouselView.
Thank you to support me.

**Comment by alexrainman** [comment] 2017-12-25 15:58
I tried to reproduce this but it works for me with your configuration :(

**Comment by alexrainman** [comment] 2017-12-25 15:59
Are you using .Net Standard? Because if you do, please downgrade to version 1.4

**Comment by nhdanh** [comment] 2017-12-26 00:54
I dont use .Net Standard.

**Comment by nhdanh** [comment] 2017-12-26 00:59
How do you reproduce this error ? Try to go back many times. All page has a scrollview. Homepage like a code in previous post.

**Comment by nhdanh** [comment] 2017-12-27 08:51
I use Prism and I use NavigateAsync with popup = true ( NavigationService.NavigateAsync(name, null, false);) 
and back button I call NavigationService.GoBackAsync(null, true);

**Comment by nhdanh** [comment] 2017-12-27 09:12
I found this problem. Sorry you, The plugin not reason crash. I have a code to autoplay CarouselView as slideshow. This code make my app crash. So I want autoplay CarouselView to slide show many image. Has your plugin support it ?

**Comment by nhdanh** [comment] 2017-12-27 09:22
Device.StartTimer(TimeSpan.FromSeconds(5), () =>
                    {
                        Position++;
                        if (Position == (ListHinhAnh.Count))
                        {
                            Position = 0;
                        }

                        return true;
                    });

I use this code to make slideshow

**Comment by dhuynh341** [comment] 2017-12-27 16:41
I'm having the same issue. If I navigate away while the carousel is animating the app will crash. Even without animation, I just swipe left and right a few times and navigate away, the app will hang (deadlock?).

**Comment by dhuynh341** [comment] 2017-12-27 19:09
My temporary fix for this issue is to wrap the carousel inside a ContentView and set the Content to null OnDisappearing.
<ContentView x:Name="contentView">
       <Carousel/>
</ContentView>

from Page.xaml.cs
override void OnDisappearing(){
    contentView.Content = null;
}

**Comment by alexrainman** [comment] 2017-12-28 01:30
I still cannot make it crash. I tested the same scenario correcting the code for AutoPlay like this:
```
Device.StartTimer(TimeSpan.FromSeconds(3), () =>
{
    if (carousel.Position < _vm.MyItemsSource.Count - 1)
    {
        carousel.Position++;
    }
    else
    {
        carousel.Position = 0;
    }
    return true;
});
```

**Comment by nhdanh** [comment] 2017-12-28 01:32
I dont know why it crash ^^. I remove this code and it work well :D

**Comment by alexrainman** [comment] 2017-12-28 01:35
It should be something in your code then.

**Comment by nhdanh** [comment] 2017-12-28 01:36
Thank you supported me.

**Comment by uksreejith** [comment] 2017-12-31 18:47
Hi @alexrainman. I am also facing the same issue. I also have a timer that increments the slide index at every unit time interval. The crash happens when you are swiping over the slides and at the same time the timer callback also tries to increment the slide index. This happens only on iOS though. On android it works fine.

**Comment by JayMansel** [comment] 2018-01-02 11:50
@uksreejith Are you updating the ItemSource when you change pages? If so there's an issue raised for that #294 . If not then not sure :)

**Comment by uksreejith** [comment] 2018-01-02 12:48
@JayMansel No.. the item source is not being updated. Only the current position is changed.. Here is my code : 
`int SlideShowUpdateInterval = Convert.ToInt32(PCLAppConfig.ConfigurationManager.AppSettings["SlideShowUpdateInterval"]) / 1000;
                Xamarin.Forms.Device.StartTimer(new TimeSpan(0, 0, SlideShowUpdateInterval), () =>
                {
                    int newPosition = cvSlideShow.Position + 1;
                    if (newPosition >= lstSlides.Count)
                        newPosition = 0;

                    cvSlideShow.Position = newPosition;
                    return true;
                });`

**Comment by uksreejith** [comment] 2018-01-02 12:49
@JayMansel No.. the item source is not being updated. Only the current position is changed.. Here is my code :
`int SlideShowUpdateInterval = Convert.ToInt32(PCLAppConfig.ConfigurationManager.AppSettings["SlideShowUpdateInterval"]) / 1000;
Xamarin.Forms.Device.StartTimer(new TimeSpan(0, 0, SlideShowUpdateInterval), () =>
{
int newPosition = cvSlideShow.Position + 1;
if (newPosition >= lstSlides.Count)
newPosition = 0;

                cvSlideShow.Position = newPosition;
                return true;
            });`

**Comment by JayMansel** [comment] 2018-01-02 13:38
@uksreejith Thanks for the info. If you were to remove your timer code, and try swiping between slides back and forth real quickly, do you get the same issue?

**Comment by alexrainman** [comment] 2018-01-02 13:51
The problem should be with the timer and not swiping back and fort.

**Comment by uksreejith** [comment] 2018-01-02 14:37
@JayMansel No it does not crash. As i stated before the crash happens only when the user and the timer callback both try to change the slide at the same time.

**Comment by alexrainman** [comment] 2018-01-02 14:40
I am adding a new property named IsSwiping to be used in cases like this. Let’s say you want to change ItemsSource or autoplay with a timer. You can check if the carousel IsSwiping before trying to so this operations.

**Comment by uksreejith** [comment] 2018-01-02 15:22
@alexrainman Yes. That would be really good!

**Comment by bondarenkod** [comment] 2018-01-29 14:32
@alexrainman Hi! 
Is it possible to get the (unstable\beta\alpha) version of this control (source code) where the IsSwiping is implemented? Or when this feature will be deployed to the nuget (beta)?
![the app exceptions from the hockey app](https://bdfss.blob.core.windows.net/shots/2018-01-29_16-30-25-fd2c99bb-3112-40c0-9ca2-d8e267d4f248.png)

**Closed** 2018-01-30 15:01 UTC
Labels: cant reproduce

**Comment by shoeIT** [comment] 2018-04-18 12:09
any news on the "isSwiping"

**Comment by BtrJay** [comment] 2018-11-15 00:33
Hi @alexrainman ,

Do you have any ETA to include 'IsSwiping' in the latest release?

I have exactly same issue with this plugin. We want to detect user's touch event while timer callback is in operation.

Regards,
Jay

**Comment by Firice** [comment] 2018-12-13 08:49
I using this plugin when more 2 page have same issue, but one or two page not problem

**Comment by aman720gupta** [comment] 2019-02-19 05:50
@alexrainman  I'm still facing this issue when I remove item from the list having carousel view can you please help me resolve same

**Comment by TobiasBuchholz** [comment] 2020-09-02 08:23
I'm also facing a similar issue with the following error message:

 NSInternalInconsistencyException Reason: No view controller managing revealed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x1602a8390; frame = (0 0; 1194 350); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x280147a80>>

For me it's quite reproducable by swiping fast through 3-4 pages and then perfom an orientation change. I'm using version 5.2.0 and an iPad 11 Pro 2020.

**Comment by leomats** [comment] 2020-09-03 19:44
Facing a similar issue, our solution is to load/initialize/update context and then assign the bindingcontext.  See snippet below:

                var context = Locator.Instance.Get<HistoryItemViewModel>();
                var tag = (DeviceAsset)parameter[0];
                var position = (int)parameter[1];
                context.Init(tag, position);
                BindingContext = context;

**Comment by CrimsonKyle** [comment] 2021-03-19 03:05
Encountered the same issue and was able to solve by simply starting the autoplay on load and stoping it on disappearing.

```
      protected override void OnAppearing()
      {
            base.OnAppearing();
            carousel.AutoplayInterval = 5;
      }

      protected override void OnDisappearing()
      {
            base.OnDisappearing();
            carousel.AutoplayInterval = 0;
      }

```
