### ISSUE TITLE
targeting Win10 build 14393 not possible after v5.0.2

### ISSUE THREAD

**Issue by craigwi** [alexrainman/CarouselView#324] opened 2018-01-21 06:09 UTC
With commit of version 5.1.0 on 1/6/2018, the project moved forward to .net standard 2.0. 

I still target Win10 build 14393 which does not support that version.  Is there some new feature that requires .net standard 2.0?

If not, can you revert to .net standard 1.4?

Thanks,
Craig.

**Comment by ruisilva450** [comment] 2018-01-22 11:21
Possible duplicate of #320

**Comment by alexrainman** [comment] 2018-01-24 02:15
Yeah, to update to NetStandard 2.0 i had to target latest platform version.

**Closed by alexrainman** 2018-01-24 02:15 UTC
